"use client";

import { useState } from "react";
import {
  ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, Clock3,
  Heart, MapPin, Menu, Minus, Phone, Play, Plus, Star, X
} from "lucide-react";
import type { DemoConfig } from "./demoData";

function Img({src, className=""}:{src:string;className?:string}) {
  return <img src={src} alt="" className={`h-full w-full object-cover transition-transform duration-700 hover:scale-[1.025] ${className}`} />;
}
function Kicker({children, dark=false}:{children:React.ReactNode;dark?:boolean}) {
  return <div className={`text-[9px] font-semibold uppercase tracking-[.22em] ${dark?"text-white/45":"opacity-45"}`}>{children}</div>;
}
function DemoNav({brand, items, dark=false}:{brand:string;items:string[];dark?:boolean}) {
  const [open,setOpen]=useState(false);
  return <header className={`sticky top-0 z-50 border-b backdrop-blur-xl ${dark?"border-white/10 bg-[#171713]/90 text-[#f0ece2]":"border-black/10 bg-white/90"}`}>
    <div className="mx-auto flex h-[70px] max-w-[1500px] items-center justify-between px-5 sm:px-8 lg:px-12">
      <a href="/demos" className="text-sm font-semibold tracking-[-.04em]">{brand}</a>
      <nav className="hidden gap-7 md:flex">{items.map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(" ","-")}`} className="text-[9px] font-semibold uppercase tracking-[.16em] opacity-55 hover:opacity-100">{x}</a>)}</nav>
      <div className="flex items-center gap-3"><a href="/demos" className="hidden text-[9px] font-semibold uppercase tracking-[.16em] opacity-45 sm:block">← Demos</a><button onClick={()=>setOpen(!open)} className="flex h-10 w-10 items-center justify-center rounded-full border md:hidden">{open?<X size={15}/>:<Menu size={15}/>}</button></div>
    </div>
    {open&&<div className="border-t px-5 py-3 md:hidden">{items.map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(" ","-")}`} onClick={()=>setOpen(false)} className="block border-b py-4 text-[9px] font-semibold uppercase tracking-[.17em] opacity-65">{x}</a>)}</div>}
  </header>;
}

export function Restaurant({c}:{c:DemoConfig}) {
  const [tab,setTab]=useState("Dinner"); const [booked,setBooked]=useState(false);
  const menu={Dinner:["Charred leek, almond, smoked cream — ₹680","Coal-roasted pumpkin, fermented chilli — ₹760","River fish, brown butter, citrus — ₹1,240","Burnt milk ice cream, jaggery — ₹520"],Drinks:["House martini, curry leaf — ₹780","Himalayan highball — ₹720","Cold brew negroni — ₹820","Zero-proof kokum spritz — ₹420"]};
  return <main className="bg-[#f3ede3] text-[#211914]"><DemoNav brand="ASTER & ASH" items={["The House","Menu","Chef","Events","Reserve"]}/>
    <section className="relative min-h-[calc(100svh-70px)] overflow-hidden bg-[#201713] text-[#f6eee3]"><Img src={c.heroImage} className="absolute inset-0 opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#17100d] via-transparent to-[#17100d]/40"/><div className="relative flex min-h-[calc(100svh-70px)] flex-col justify-between p-6 sm:p-10 lg:p-16"><div className="flex justify-between text-[8px] uppercase tracking-[.22em] text-white/50"><span>New Delhi / Modern Indian</span><span>07 PM — Late</span></div><div><Kicker dark>Kitchen / Table / Fire</Kicker><h1 className="mt-5 max-w-6xl font-serif text-[clamp(4.8rem,12vw,12rem)] leading-[.72] tracking-[-.07em]">Dinner worth<br/><i className="text-[#c47b55]">remembering.</i></h1><div className="mt-8 flex flex-wrap gap-3"><a href="#reserve" className="rounded-full bg-[#f6eee3] px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-[#211914]">Reserve a table ↗</a><a href="#menu" className="rounded-full border border-white/30 px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em]">View tonight's menu</a></div></div><div className="grid max-w-3xl grid-cols-3 gap-4 border-t border-white/20 pt-4 text-[8px] uppercase tracking-[.15em] text-white/45"><span>Seasonal menu</span><span>Chef's table</span><span>Private dining</span></div></div></section>
    <section id="the-house" className="grid lg:grid-cols-[.7fr_1.3fr]"><div className="bg-[#c77c58] p-7 text-[#211914] sm:p-12 lg:p-16"><Kicker>01 / The house</Kicker><h2 className="mt-20 font-serif text-[clamp(3.2rem,7vw,7rem)] leading-[.8] tracking-[-.06em]">A room for<br/><i>long evenings.</i></h2></div><div className="p-7 sm:p-12 lg:p-20"><p className="max-w-3xl font-serif text-[clamp(2rem,4vw,4.5rem)] leading-[.95] tracking-[-.045em]">Aster & Ash is built around the idea that dinner should unfold, not be rushed.</p><div className="mt-16 grid gap-10 border-t border-black/10 pt-8 sm:grid-cols-3"><div><strong>04</strong><p className="mt-2 text-[9px] uppercase tracking-[.16em] opacity-45">Dining rooms</p></div><div><strong>12</strong><p className="mt-2 text-[9px] uppercase tracking-[.16em] opacity-45">Seasonal plates</p></div><div><strong>01</strong><p className="mt-2 text-[9px] uppercase tracking-[.16em] opacity-45">Chef's table</p></div></div></div></section>
    <section id="menu" className="bg-[#241915] px-5 py-24 text-[#f4eadf] sm:px-10 lg:px-16"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><Kicker dark>02 / Tonight</Kicker><h2 className="mt-4 font-serif text-[clamp(4rem,9vw,9rem)] leading-[.72] tracking-[-.07em]">The menu.</h2></div><div className="flex rounded-full border border-white/15 p-1">{["Dinner","Drinks"].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-5 py-2 text-[8px] uppercase tracking-[.16em] ${tab===x?"bg-[#f4eadf] text-[#241915]":""}`}>{x}</button>)}</div></div><div className="mt-14 grid gap-x-10 md:grid-cols-2">{menu[tab as keyof typeof menu].map((x,i)=><div key={x} className="flex gap-5 border-t border-white/10 py-7"><span className="font-mono text-[9px] text-white/25">0{i+1}</span><span className="text-lg leading-6">{x}</span></div>)}</div></section>
    <section id="chef" className="grid lg:grid-cols-2"><div className="min-h-[520px]"><Img src={c.featureImage}/></div><div className="flex flex-col justify-center bg-[#e5d4c1] p-7 sm:p-12 lg:p-20"><Kicker>03 / The kitchen</Kicker><h2 className="mt-6 max-w-2xl font-serif text-[clamp(3.2rem,6vw,6rem)] leading-[.82]">Technique with a sense of place.</h2><p className="mt-7 max-w-xl text-sm leading-7 opacity-60">{c.featureBody} Our kitchen changes with the market, but the philosophy stays simple: honest ingredients, precise fire and food that leaves a memory.</p><a href="#reserve" className="mt-9 flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.18em]">Meet the kitchen <ArrowUpRight size={14}/></a></div></section>
    <section id="events" className="px-5 py-24 sm:px-10 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><Kicker>04 / Beyond dinner</Kicker><h2 className="mt-5 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">More ways<br/><i>to gather.</i></h2></div><div className="space-y-0">{["Chef's table / Six seats / Monthly","Sunday lunch / Seasonal / 12–4 PM","Private dining / 10–28 guests / By request","Kitchen counter / Four courses / Fridays"].map((x,i)=><div key={x} className="flex items-center justify-between border-b py-7"><span><small className="mr-4 font-mono text-[9px] opacity-30">0{i+1}</small>{x}</span><ArrowRight size={15}/></div>)}</div></div></section>
    <section id="reserve" className="bg-[#c77c58] px-5 py-20 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-[1400px] gap-10 lg:grid-cols-[1fr_.75fr]"><div><Kicker>05 / Reservations</Kicker><h2 className="mt-5 max-w-3xl font-serif text-[clamp(4rem,8vw,8rem)] leading-[.75]">Save your<br/><i>seat.</i></h2><p className="mt-7 max-w-lg text-sm leading-7 opacity-65">For parties larger than eight, private dining or special occasions, speak directly with our team.</p></div><form onSubmit={e=>{e.preventDefault();setBooked(true)}} className="rounded-[24px] bg-[#f3ede3] p-6 sm:p-8">{booked?<div className="py-12"><Check size={24}/><h3 className="mt-5 font-serif text-4xl">You're on the list.</h3><p className="mt-3 text-sm opacity-55">Demo confirmation — a production build can connect this flow to a reservation provider.</p></div>:<><div className="grid gap-3 sm:grid-cols-2"><input required placeholder="Name" className="h-14 rounded-xl border border-black/10 bg-transparent px-4 text-sm"/><input required placeholder="Guests" className="h-14 rounded-xl border border-black/10 bg-transparent px-4 text-sm"/><input required type="date" className="h-14 rounded-xl border border-black/10 bg-transparent px-4 text-sm"/><select className="h-14 rounded-xl border border-black/10 bg-transparent px-4 text-sm"><option>7:30 PM</option><option>8:30 PM</option><option>9:30 PM</option></select></div><textarea placeholder="Occasion or notes" rows={4} className="mt-3 w-full rounded-xl border border-black/10 bg-transparent p-4 text-sm"/><button className="mt-3 flex h-14 w-full items-center justify-between rounded-xl bg-[#241915] px-5 text-[9px] font-bold uppercase tracking-[.16em] text-white">Check availability <ArrowUpRight size={15}/></button></>}</form></div></section>
    <footer className="px-5 py-10 text-[8px] uppercase tracking-[.17em] opacity-45 sm:px-10">Aster & Ash / New Delhi / Concept by Ganlary Labs / Demo website</footer>
  </main>;
}

export function Clinic({c}:{c:DemoConfig}) {
 const [active,setActive]=useState(0); const [book,setBook]=useState(false);
 const treatments=["General & preventive","Cosmetic dentistry","Implants & restoration","Orthodontics","Emergency care"];
 return <main className="bg-[#f4f7f4] text-[#12312f]"><div className="bg-[#12312f] px-5 py-2 text-center text-[8px] uppercase tracking-[.18em] text-white/65">Open today until 8 PM · Same-day emergency appointments</div><DemoNav brand="NORTHLINE / DENTAL" items={["Why Northline","Treatments","Doctors","Patients","Book"]}/>
 <section className="grid min-h-[calc(100svh-100px)] lg:grid-cols-[.85fr_1.15fr]"><div className="flex flex-col justify-between p-6 sm:p-10 lg:p-14"><div><Kicker>Family dental studio / Guwahati</Kicker><h1 className="mt-8 max-w-3xl text-[clamp(4.3rem,9vw,9rem)] font-medium leading-[.78] tracking-[-.08em]">Your family's<br/><i className="font-serif font-normal text-[#0f716a]">smile, cared for.</i></h1><p className="mt-8 max-w-xl text-sm leading-7 opacity-55">{c.heroBody}</p></div><div className="mt-12 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-black/10 bg-black/10 sm:grid-cols-4">{[["4.9/5","Patient rating"],["12+","Treatment areas"],["08:00","Doors open"],["24h","Follow-up"]].map(x=><div key={x[1]} className="bg-[#f4f7f4] p-4"><strong>{x[0]}</strong><p className="mt-1 text-[7px] uppercase tracking-[.14em] opacity-45">{x[1]}</p></div>)}</div></div><div className="relative min-h-[520px]"><Img src={c.heroImage}/><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-[#f4f7f4]/95 p-5 shadow-xl backdrop-blur"><div className="flex items-center justify-between"><div><div className="text-[8px] uppercase tracking-[.15em] opacity-45">New patient?</div><div className="mt-1 text-lg">Find a time that works.</div></div><a href="#book" className="rounded-full bg-[#0f716a] px-4 py-3 text-[8px] font-bold uppercase tracking-[.14em] text-white">Book ↗</a></div></div></div></section>
 <section id="why-northline" className="border-y border-black/10 px-5 py-20 sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.55fr_1.45fr]"><div><Kicker>01 / Patient first</Kicker><p className="mt-6 font-serif text-4xl leading-[.95]">Good healthcare starts with knowing what happens next.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-black/10 bg-black/10 md:grid-cols-2"><div className="bg-white p-7"><Clock3 size={18}/><h3 className="mt-12 text-2xl">Less waiting</h3><p className="mt-3 text-sm leading-6 opacity-50">Choose a slot online, receive a clear confirmation and arrive knowing what to expect.</p></div><div className="bg-white p-7"><Heart size={18}/><h3 className="mt-12 text-2xl">More listening</h3><p className="mt-3 text-sm leading-6 opacity-50">Consultations begin with your concerns, not a checklist.</p></div><div className="bg-white p-7"><Phone size={18}/><h3 className="mt-12 text-2xl">Human support</h3><p className="mt-3 text-sm leading-6 opacity-50">Questions before or after treatment? Our care team stays reachable.</p></div><div className="bg-[#dcebe7] p-7"><Check size={18}/><h3 className="mt-12 text-2xl">Clear plans</h3><p className="mt-3 text-sm leading-6 opacity-50">We explain options, timelines and next steps in plain language.</p></div></div></div></section>
 <section id="treatments" className="bg-[#12312f] px-5 py-24 text-[#f1f6f2] sm:px-10 lg:px-16"><div className="mx-auto max-w-[1400px]"><Kicker dark>02 / Treatment finder</Kicker><div className="mt-7 grid gap-10 lg:grid-cols-[.55fr_1.45fr]"><div><h2 className="font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">What can<br/><i className="text-[#8ebbb2]">we help with?</i></h2><p className="mt-6 text-sm leading-7 text-white/45">Start with the reason you're visiting. We'll show you the path.</p></div><div>{treatments.map((x,i)=><button key={x} onClick={()=>setActive(i)} className="flex w-full items-center justify-between border-b border-white/10 py-6 text-left"><span><span className="mr-5 font-mono text-[9px] text-white/25">0{i+1}</span><strong className="text-xl font-normal sm:text-3xl">{x}</strong>{active===i&&<span className="mt-2 ml-10 block max-w-lg text-sm leading-6 text-white/40">{c.services[Math.min(i,3)].description}</span>}</span>{active===i?<Minus size={16}/>:<Plus size={16}/>}</button>)}</div></div></div></section>
 <section id="doctors" className="grid lg:grid-cols-[1.1fr_.9fr]"><div className="p-7 sm:p-12 lg:p-20"><Kicker>03 / Your care team</Kicker><h2 className="mt-6 max-w-3xl text-[clamp(3.3rem,6vw,6.5rem)] leading-[.82] tracking-[-.07em]">Specialists who explain, not overwhelm.</h2><div className="mt-12 space-y-0">{["Dr. Mira Sen / Restorative & cosmetic","Dr. Arjun Bora / Implants & surgery","Dr. Naina Das / Orthodontics","Dr. Rhea Kapoor / Family dentistry"].map((x,i)=><div key={x} className="flex justify-between border-t border-black/10 py-5 text-sm"><span><span className="mr-4 font-mono text-[8px] opacity-35">0{i+1}</span>{x}</span><ArrowUpRight size={14}/></div>)}</div></div><Img src={c.featureImage}/></section>
 <section id="patients" className="bg-[#dcebe7] px-5 py-24 sm:px-10 lg:px-16"><Kicker>04 / Patient guide</Kicker><div className="mt-10 grid gap-4 md:grid-cols-3">{["Your first visit","Understanding treatment","Aftercare & follow-up"].map((x,i)=><article key={x} className="rounded-3xl bg-white p-7"><span className="font-mono text-[9px] opacity-35">0{i+1}</span><h3 className="mt-20 text-2xl">{x}</h3><p className="mt-3 text-sm leading-6 opacity-50">A simple guide covering what to bring, what we'll discuss and the questions worth asking.</p><a className="mt-8 block text-[8px] font-bold uppercase tracking-[.16em] text-[#0f716a]">Read guide ↗</a></article>)}</div></section>
 <section id="book" className="px-5 py-20 sm:px-10 lg:px-16"><div className="rounded-[30px] bg-[#0f716a] p-7 text-white sm:p-12 lg:p-16"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><Kicker dark>05 / Appointments</Kicker><h2 className="mt-6 font-serif text-[clamp(4rem,8vw,8rem)] leading-[.75]">Let's make the<br/><i>next visit easy.</i></h2><p className="mt-7 max-w-lg text-sm leading-7 text-white/60">Tell us what you need. This demo can connect to a real calendar, CRM or WhatsApp flow.</p></div><form onSubmit={e=>{e.preventDefault();setBook(true)}} className="rounded-3xl bg-[#f4f7f4] p-5 text-[#12312f] sm:p-7">{book?<div className="py-10"><Check/><h3 className="mt-4 text-3xl">Request received.</h3><p className="mt-2 text-sm opacity-50">Demo success state.</p></div>:<><input required placeholder="Your name" className="h-14 w-full rounded-xl border border-black/10 px-4"/><input required placeholder="Phone number" className="mt-3 h-14 w-full rounded-xl border border-black/10 px-4"/><select className="mt-3 h-14 w-full rounded-xl border border-black/10 px-4"><option>New patient consultation</option><option>Existing patient</option><option>Emergency</option></select><button className="mt-3 h-14 w-full rounded-xl bg-[#12312f] text-[9px] font-bold uppercase tracking-[.16em] text-white">Request appointment</button></>}</form></div></div></section>
 <footer className="px-5 py-10 text-[8px] uppercase tracking-[.17em] opacity-40 sm:px-10">Northline Dental / Guwahati / Concept by Ganlary Labs / Demo website</footer></main>;
}

export function RealEstate({c}:{c:DemoConfig}) {
 const [filter,setFilter]=useState("All"); const types=["All","Homes","Apartments","Land"];
 return <main className="bg-[#171713] text-[#eee9dc]"><DemoNav brand="NORTH & FORM" items={["Journal","Properties","Places","Advisors","Enquire"]} dark/>
 <section className="relative min-h-[90svh] overflow-hidden"><Img src={c.heroImage} className="absolute inset-0 opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-[#171713] via-transparent to-[#171713]/25"/><div className="relative flex min-h-[90svh] flex-col justify-between p-6 sm:p-10 lg:p-16"><div className="flex justify-between text-[8px] uppercase tracking-[.22em] text-white/45"><span>Selected property / Northeast India</span><span>Issue 06 / 2026</span></div><div><Kicker dark>Property / Architecture / Place</Kicker><h1 className="mt-5 max-w-6xl font-serif text-[clamp(4.8rem,12vw,12rem)] font-normal leading-[.7] tracking-[-.075em]">Find a place<br/><i className="text-[#c8a66a]">with presence.</i></h1><p className="mt-8 max-w-xl text-sm leading-7 text-white/55">{c.heroBody}</p></div></div></section>
 <section id="journal" className="bg-[#eee9dc] px-5 py-24 text-[#171713] sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.4fr_1.6fr]"><div><Kicker>01 / Journal</Kicker><p className="mt-5 text-xs leading-6 opacity-45">Stories about architecture, ownership and the neighbourhoods shaping the next generation of homes.</p></div><div className="grid gap-8 md:grid-cols-2"><article><Img src={c.gallery[0]} className="aspect-[1.15]"/><div className="mt-4 text-[8px] uppercase tracking-[.16em] opacity-40">Architecture / 06 min</div><h3 className="mt-2 font-serif text-3xl">Why quiet architecture ages better.</h3></article><article><Img src={c.gallery[1]} className="aspect-[1.15]"/><div className="mt-4 text-[8px] uppercase tracking-[.16em] opacity-40">Neighbourhood / 04 min</div><h3 className="mt-2 font-serif text-3xl">A slower way to choose where you live.</h3></article></div></div></section>
 <section id="properties" className="px-5 py-24 sm:px-10 lg:px-16"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><Kicker dark>02 / The collection</Kicker><h2 className="mt-5 font-serif text-[clamp(4rem,8vw,8rem)] leading-[.73]">Places worth<br/><i className="text-[#c8a66a]">seeing.</i></h2></div><div className="flex flex-wrap gap-2">{types.map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full border px-4 py-2 text-[8px] uppercase tracking-[.15em] ${filter===x?"border-[#c8a66a] bg-[#c8a66a] text-[#171713]":"border-white/15"}`}>{x}</button>)}</div></div><div className="mt-14 grid gap-10 md:grid-cols-2">{c.gallery.map((img,i)=><article key={img} className="group"><div className="relative overflow-hidden"><Img src={img} className="aspect-[1.15]"/><span className="absolute left-4 top-4 rounded-full bg-[#171713]/60 px-3 py-2 text-[8px] uppercase tracking-[.16em] text-white backdrop-blur">{filter==="All"?["Homes","Apartments","Land","Homes"][i]:filter}</span></div><div className="flex items-end justify-between border-b border-white/10 py-5"><div><div className="text-[8px] uppercase tracking-[.15em] text-white/35">0{i+1} / {["Ridge House","The Courtyard","Forest Residence","Hill House"][i]}</div><h3 className="mt-2 text-2xl">A considered address</h3><p className="mt-2 text-xs text-white/40">3 bed · 2,480 sq ft · Private garden · From ₹1.8Cr</p></div><ArrowUpRight/></div></article>)}</div></section>
 <section id="places" className="grid bg-[#24241f] lg:grid-cols-2"><div className="p-7 sm:p-12 lg:p-20"><Kicker dark>03 / The neighbourhood</Kicker><h2 className="mt-6 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.78]">A home is<br/><i className="text-[#c8a66a]">more than walls.</i></h2><p className="mt-8 max-w-xl text-sm leading-7 text-white/45">We map the everyday around every property: schools, cafés, parks, commutes, markets and the places you'll actually use.</p><div className="mt-12 space-y-0">{["Cafés within 8 min","Schools within 15 min","Airport within 32 min","Weekend trails within 20 min"].map((x,i)=><div key={x} className="flex justify-between border-t border-white/10 py-5 text-sm"><span>0{i+1} / {x}</span><ArrowUpRight size={14}/></div>)}</div></div><Img src={c.featureImage}/></section>
 <section id="advisors" className="px-5 py-24 sm:px-10 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Kicker dark>04 / Advisors</Kicker><h2 className="mt-5 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">A person<br/>behind every<br/><i className="text-[#c8a66a]">property.</i></h2></div><div className="space-y-5">{["Aarav Mehta / Residential","Maya Dutta / Architecture-led homes","Rohan Sen / Land & estates"].map((x,i)=><div key={x} className="flex items-center justify-between border-b border-white/10 py-6"><span><small className="mr-5 font-mono text-[9px] text-white/25">0{i+1}</small>{x}</span><span className="text-[8px] uppercase tracking-[.15em] text-white/35">View profile ↗</span></div>)}</div></div></section>
 <section id="enquire" className="bg-[#c8a66a] px-5 py-20 text-[#171713] sm:px-10 lg:px-16"><div className="mx-auto max-w-[1300px]"><Kicker>05 / Private enquiry</Kicker><h2 className="mt-5 max-w-5xl font-serif text-[clamp(4rem,9vw,9rem)] leading-[.72]">Find your next<br/><i>address.</i></h2><div className="mt-12 grid gap-3 sm:grid-cols-3"><input placeholder="Name" className="h-14 rounded-xl bg-[#eee9dc] px-4"/><input placeholder="Email" className="h-14 rounded-xl bg-[#eee9dc] px-4"/><button className="h-14 rounded-xl bg-[#171713] text-[9px] font-bold uppercase tracking-[.16em] text-white">Request a viewing ↗</button></div></div></section>
 <footer className="px-5 py-10 text-[8px] uppercase tracking-[.17em] text-white/35 sm:px-10">North & Form / Selected homes / Concept by Ganlary Labs / Demo website</footer></main>;
}

export function Salon({c}:{c:DemoConfig}) {
 const [active,setActive]=useState(0); const services=["Cut & Style","Colour Studio","Skin & Body","Bridal"];
 return <main className="bg-[#f0e7e4] text-[#2c2021]"><DemoNav brand="MORROW" items={["House","Services","Artists","Journal","Book"]}/>
 <section className="grid min-h-[calc(100svh-70px)] lg:grid-cols-[.78fr_1.22fr]"><div className="order-2 flex flex-col justify-between p-6 sm:p-10 lg:order-1 lg:p-16"><div><Kicker>Beauty / Wellness house</Kicker><h1 className="mt-8 font-serif text-[clamp(5rem,12vw,12rem)] leading-[.67] tracking-[-.075em]">Your ritual,<br/><i className="text-[#9a5d64]">reimagined.</i></h1><p className="mt-8 max-w-lg text-sm leading-7 opacity-55">{c.heroBody}</p></div><div className="mt-12 flex flex-wrap gap-3"><a href="#services" className="rounded-full bg-[#9a5d64] px-5 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-white">Book your visit ↗</a><a href="#artists" className="rounded-full border border-black/15 px-5 py-3 text-[9px] font-bold uppercase tracking-[.16em]">Meet the artists</a></div></div><div className="order-1 min-h-[540px] lg:order-2"><Img src={c.heroImage}/></div></section>
 <section id="house" className="bg-[#2c2021] px-5 py-24 text-[#f3e9e6] sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.4fr_1.6fr]"><div><Kicker dark>01 / The house</Kicker></div><div><p className="max-w-5xl font-serif text-[clamp(3rem,6vw,6.5rem)] leading-[.84]">Beauty is a feeling before it is a service. Morrow makes space for both.</p><div className="mt-14 grid grid-cols-2 border-y border-white/10 sm:grid-cols-4">{[["18","Services"],["07","Artists"],["10 AM","First appointment"],["90m","Signature ritual"]].map(x=><div key={x[1]} className="border-r border-white/10 p-5 last:border-0"><strong>{x[0]}</strong><p className="mt-2 text-[8px] uppercase tracking-[.15em] text-white/40">{x[1]}</p></div>)}</div></div></div></section>
 <section id="services" className="px-5 py-24 sm:px-10 lg:px-16"><div className="flex items-end justify-between"><div><Kicker>02 / Services</Kicker><h2 className="mt-5 font-serif text-[clamp(4rem,8vw,8rem)] leading-[.72]">Choose your<br/><i className="text-[#9a5d64]">ritual.</i></h2></div><span className="hidden text-[8px] uppercase tracking-[.16em] opacity-35 sm:block">Duration + starting price</span></div><div className="mt-14 border-t border-black/10">{services.map((x,i)=><button key={x} onClick={()=>setActive(i)} className="grid w-full grid-cols-[35px_1fr_auto] gap-3 border-b border-black/10 py-7 text-left sm:grid-cols-[70px_1fr_auto] sm:py-9"><span className="font-mono text-[9px] opacity-30">0{i+1}</span><span><strong className="font-serif text-2xl font-normal sm:text-4xl">{x}</strong>{active===i&&<span className="mt-2 block max-w-xl text-sm leading-6 opacity-50">{c.services[i].description}</span>}</span><span className="text-[8px] uppercase tracking-[.14em] opacity-45">{["60 min / ₹1,800","120 min / ₹4,500","75 min / ₹2,800","By consultation"][i]}</span></button>)}</div></section>
 <section id="artists" className="bg-[#d9c5c3] px-5 py-24 sm:px-10 lg:px-16"><Kicker>03 / Artists</Kicker><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{c.gallery.slice(0,3).map((img,i)=><article key={img}><div className="aspect-[.82] overflow-hidden"><Img src={img}/></div><div className="mt-4 flex justify-between"><div><h3 className="text-xl">{["Anika / Hair","Meera / Colour","Rhea / Skin"][i]}</h3><p className="mt-1 text-[8px] uppercase tracking-[.15em] opacity-45">{["Cuts + texture","Colour + gloss","Skin + ritual"][i]}</p></div><ArrowUpRight size={15}/></div></article>)}</div></section>
 <section id="journal" className="px-5 py-24 sm:px-10 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><Kicker>04 / Journal</Kicker><h2 className="mt-5 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">Notes from<br/><i>the studio.</i></h2></div><div className="space-y-0">{["How to make a colour appointment work harder","The Morrow guide to slower mornings","What to bring to your first skin ritual","Bridal beauty: start six months early"].map((x,i)=><div key={x} className="flex items-center justify-between border-b border-black/10 py-6 text-sm"><span><small className="mr-5 font-mono text-[8px] opacity-30">0{i+1}</small>{x}</span><ArrowUpRight size={14}/></div>)}</div></div></section>
 <section id="book" className="bg-[#9a5d64] px-5 py-20 text-white sm:px-10 lg:px-16"><Kicker dark>05 / Booking</Kicker><h2 className="mt-5 max-w-5xl font-serif text-[clamp(4rem,9vw,9rem)] leading-[.72]">Make time<br/><i>for yourself.</i></h2><div className="mt-10 grid gap-3 sm:grid-cols-3"><button className="h-14 rounded-xl bg-white text-[9px] font-bold uppercase tracking-[.16em] text-[#2c2021]">Choose a service</button><button className="h-14 rounded-xl border border-white/30 text-[9px] font-bold uppercase tracking-[.16em]">Choose an artist</button><button className="h-14 rounded-xl border border-white/30 text-[9px] font-bold uppercase tracking-[.16em]">Find a time ↗</button></div></section><footer className="px-5 py-10 text-[8px] uppercase tracking-[.17em] opacity-40 sm:px-10">Morrow / Bengaluru / Concept by Ganlary Labs / Demo website</footer></main>;
}

export function Education({c}:{c:DemoConfig}) {
 const [program,setProgram]=useState(0);
 return <main className="bg-[#f3f0e8] text-[#1d251f]"><DemoNav brand="NORTHSTAR ACADEMY" items={["Idea","Programs","Mentors","Projects","Apply"]}/>
 <section className="px-5 pb-16 pt-10 sm:px-10 lg:px-16"><div className="mx-auto max-w-[1500px]"><div className="flex justify-between text-[8px] uppercase tracking-[.2em] opacity-40"><span>Career education / India</span><span>Next cohort / Jan 2027</span></div><div className="mt-14 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><Kicker>Learn / Build / Launch</Kicker><h1 className="mt-6 max-w-6xl text-[clamp(4.5rem,11vw,11rem)] font-medium leading-[.72] tracking-[-.085em]">Learn what<br/><i className="font-serif font-normal text-[#315f4a]">moves you forward.</i></h1><p className="mt-8 max-w-xl text-base leading-7 opacity-55">{c.heroBody}</p><a href="#programs" className="mt-8 inline-flex rounded-full bg-[#315f4a] px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-white">Find your program ↗</a></div><div className="aspect-[.9] overflow-hidden rounded-[28px]"><Img src={c.heroImage}/></div></div></div></section>
 <section id="idea" className="bg-[#315f4a] px-5 py-24 text-[#f2f1e9] sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.35fr_1.65fr]"><Kicker dark>01 / The idea</Kicker><div><h2 className="max-w-6xl font-serif text-[clamp(3.2rem,7vw,7rem)] leading-[.8]">Learning should change what you can do.</h2><p className="mt-8 max-w-2xl text-base leading-8 text-white/55">Northstar is designed around visible work: projects, feedback, mentors and outcomes. Less passive watching. More evidence that you've learned something.</p><div className="mt-14 grid grid-cols-2 border-y border-white/10 sm:grid-cols-4">{[["14","Programs"],["32","Mentors"],["87%","Project completion"],["06","Week sprints"]].map(x=><div key={x[1]} className="border-r border-white/10 p-5 last:border-0"><strong>{x[0]}</strong><p className="mt-2 text-[8px] uppercase tracking-[.15em] text-white/40">{x[1]}</p></div>)}</div></div></div></section>
 <section id="programs" className="px-5 py-24 sm:px-10 lg:px-16"><div className="flex items-end justify-between"><div><Kicker>02 / Programs</Kicker><h2 className="mt-5 text-[clamp(4rem,8vw,8rem)] font-medium leading-[.72] tracking-[-.07em]">Choose your<br/><i className="font-serif font-normal text-[#315f4a]">direction.</i></h2></div><span className="hidden text-[8px] uppercase tracking-[.16em] opacity-35 sm:block">Projects included</span></div><div className="mt-14 grid gap-3 lg:grid-cols-2">{c.services.map((s,i)=><button key={s.name} onClick={()=>setProgram(i)} className={`rounded-[25px] border p-7 text-left transition-transform hover:-translate-y-1 sm:p-9 ${program===i?"border-[#315f4a] bg-[#dfe5da]":"border-black/10"}`}><div className="flex justify-between"><span className="font-mono text-[9px] opacity-30">{s.number}</span><ArrowUpRight size={15}/></div><h3 className="mt-16 text-3xl tracking-[-.04em]">{s.name}</h3><p className="mt-3 max-w-md text-sm leading-6 opacity-50">{s.description}</p><div className="mt-8 flex gap-5 text-[8px] uppercase tracking-[.15em] opacity-45"><span>06 weeks</span><span>Live mentor</span><span>3 projects</span></div></button>)}</div></section>
 <section id="mentors" className="grid lg:grid-cols-[.85fr_1.15fr]"><Img src={c.featureImage}/><div className="p-7 sm:p-12 lg:p-20"><Kicker>03 / Mentors</Kicker><h2 className="mt-6 max-w-3xl text-[clamp(3.5rem,7vw,7rem)] leading-[.78] tracking-[-.07em]">Learn with people who still do the work.</h2><div className="mt-12 space-y-0">{["Aisha Roy / Product design","Kabir Menon / Software engineering","Nikhil Das / Data & AI","Rhea Sen / Growth"].map((x,i)=><div key={x} className="flex justify-between border-t border-black/10 py-5 text-sm"><span><small className="mr-5 font-mono text-[8px] opacity-30">0{i+1}</small>{x}</span><span className="text-[8px] uppercase tracking-[.15em] opacity-35">Profile ↗</span></div>)}</div></div></section>
 <section id="projects" className="bg-[#dfe5da] px-5 py-24 sm:px-10 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><Kicker>04 / Proof of work</Kicker><h2 className="mt-5 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">Don't just<br/><i>learn it.</i><br/>build it.</h2></div><div className="grid gap-4 sm:grid-cols-2">{["AI research assistant","Revenue dashboard","Creator analytics product","Local commerce platform"].map((x,i)=><article key={x} className="rounded-3xl bg-[#f3f0e8] p-6"><span className="font-mono text-[9px] opacity-30">PROJECT 0{i+1}</span><h3 className="mt-20 text-xl">{x}</h3><p className="mt-3 text-sm leading-6 opacity-45">Brief → research → build → feedback → final presentation.</p></article>)}</div></div></section>
 <section id="apply" className="px-5 py-20 sm:px-10 lg:px-16"><div className="rounded-[30px] bg-[#1d251f] p-7 text-[#f3f0e8] sm:p-12 lg:p-16"><Kicker dark>05 / Applications</Kicker><h2 className="mt-5 max-w-5xl font-serif text-[clamp(4rem,9vw,9rem)] leading-[.72]">Build your<br/><i className="text-[#8fb19e]">next chapter.</i></h2><div className="mt-10 flex flex-wrap gap-3"><button className="rounded-full bg-[#f3f0e8] px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-[#1d251f]">Check eligibility ↗</button><button className="rounded-full border border-white/20 px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em]">Download curriculum</button></div></div></section><footer className="px-5 py-10 text-[8px] uppercase tracking-[.17em] opacity-40 sm:px-10">Northstar Academy / India + online / Concept by Ganlary Labs / Demo website</footer></main>;
}

export function LocalService({c}:{c:DemoConfig}) {
 const [selected,setSelected]=useState(0); const [sent,setSent]=useState(false);
 return <main className="bg-[#eee9de] text-[#20251f]"><div className="bg-[#20251f] px-5 py-2 text-center text-[8px] uppercase tracking-[.18em] text-white/60">Available 7 days · Response usually within 60 minutes</div><DemoNav brand="FIELD & FORM" items={["Why us","Services","Work","Areas","Quote"]}/>
 <section className="grid min-h-[calc(100svh-100px)] lg:grid-cols-[1.05fr_.95fr]"><div className="flex flex-col justify-between p-6 sm:p-10 lg:p-16"><div><Kicker>Property care / Guwahati + nearby</Kicker><h1 className="mt-8 max-w-5xl text-[clamp(4.5rem,11vw,11rem)] font-medium leading-[.72] tracking-[-.085em]">Good work,<br/><i className="font-serif font-normal text-[#b46d32]">done properly.</i></h1><p className="mt-8 max-w-xl text-base leading-7 opacity-55">{c.heroBody}</p></div><div className="mt-10 flex gap-3"><a href="#quote" className="rounded-full bg-[#b46d32] px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-white">Request a quote ↗</a><a href="#services" className="rounded-full border border-black/15 px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em]">See services</a></div></div><div className="relative min-h-[520px]"><Img src={c.heroImage}/><div className="absolute bottom-5 left-5 right-5 grid grid-cols-2 gap-px overflow-hidden rounded-2xl bg-black/10 shadow-xl"><div className="bg-[#eee9de]/95 p-5"><div className="text-[8px] uppercase tracking-[.15em] opacity-45">Response</div><strong className="mt-2 block">Within 60 min</strong></div><div className="bg-[#eee9de]/95 p-5"><div className="text-[8px] uppercase tracking-[.15em] opacity-45">Coverage</div><strong className="mt-2 block">7 days a week</strong></div></div></div></section>
 <section id="why-us" className="bg-[#20251f] px-5 py-24 text-[#eee9de] sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.35fr_1.65fr]"><Kicker dark>01 / Why Field & Form</Kicker><div><h2 className="max-w-5xl font-serif text-[clamp(3.3rem,7vw,7rem)] leading-[.8]">The people you call when it needs doing right.</h2><div className="mt-14 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 p-6"><Check/><h3 className="mt-12 text-xl">Clear quotes</h3><p className="mt-2 text-sm leading-6 text-white/40">No mystery pricing or vague arrival windows.</p></div><div className="rounded-2xl border border-white/10 p-6"><Clock3/><h3 className="mt-12 text-xl">Fast response</h3><p className="mt-2 text-sm leading-6 text-white/40">Urgent requests have a direct route to the team.</p></div><div className="rounded-2xl border border-white/10 p-6"><Heart/><h3 className="mt-12 text-xl">People you trust</h3><p className="mt-2 text-sm leading-6 text-white/40">The same standard whether it's one room or an entire property.</p></div></div></div></div></section>
 <section id="services" className="px-5 py-24 sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.55fr_1.45fr]"><div><Kicker>02 / Services</Kicker><h2 className="mt-5 text-[clamp(3.8rem,8vw,8rem)] leading-[.72] tracking-[-.08em]">Tell us what<br/><i className="font-serif font-normal text-[#b46d32]">needs doing.</i></h2></div><div className="border-t border-black/10">{c.services.map((s,i)=><button key={s.name} onClick={()=>setSelected(i)} className="w-full border-b border-black/10 py-7 text-left"><div className="flex items-center justify-between"><span><small className="mr-5 font-mono text-[8px] opacity-30">{s.number}</small><strong className="text-2xl font-medium sm:text-4xl">{s.name}</strong></span>{selected===i?<Minus size={16}/>:<Plus size={16}/>}</div>{selected===i&&<div className="ml-8 mt-4 max-w-xl text-sm leading-7 opacity-50">{s.description}<div className="mt-4 text-[8px] font-bold uppercase tracking-[.16em] text-[#b46d32]">Typical response / 60 min ↗</div></div>}</button>)}</div></div></section>
 <section id="work" className="bg-[#d8d0c2] px-5 py-24 sm:px-10 lg:px-16"><div className="flex items-end justify-between"><div><Kicker>03 / Recent work</Kicker><h2 className="mt-5 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">Work that<br/><i>speaks.</i></h2></div><span className="hidden text-[8px] uppercase tracking-[.15em] opacity-40 sm:block">Before / After / Detail</span></div><div className="mt-12 grid gap-4 md:grid-cols-2"><Img src={c.gallery[0]} className="aspect-[1.15]"/><div className="grid gap-4"><Img src={c.gallery[1]} className="aspect-[1.15]"/><div className="grid grid-cols-2 gap-4"><Img src={c.gallery[2]} className="aspect-square"/><div className="flex flex-col justify-end rounded-3xl bg-[#eee9de] p-6"><span className="font-mono text-[8px] opacity-35">PROJECT 04</span><h3 className="mt-16 text-2xl">Move-in reset</h3><p className="mt-2 text-sm leading-6 opacity-45">Deep clean, minor repairs and final walkthrough.</p></div></div></div></div></section>
 <section id="areas" className="px-5 py-24 sm:px-10 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><Kicker>04 / Service areas</Kicker><h2 className="mt-5 text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">Close enough<br/>to show up.</h2></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-3xl border border-black/10 bg-black/10 sm:grid-cols-3">{["Guwahati","Dispur","Six Mile","Beltola","Kahilipara","Jalukbari","Airport corridor","Nearby estates","Commercial"].map(x=><div key={x} className="bg-[#eee9de] p-5 text-sm">{x}<MapPin size={13} className="mt-7 opacity-35"/></div>)}</div></div></section>
 <section id="quote" className="bg-[#b46d32] px-5 py-20 text-white sm:px-10 lg:px-16"><div className="mx-auto grid max-w-[1400px] gap-10 lg:grid-cols-[1fr_.8fr]"><div><Kicker dark>05 / Quote request</Kicker><h2 className="mt-5 font-serif text-[clamp(4rem,9vw,9rem)] leading-[.72]">Tell us what<br/><i>needs doing.</i></h2><p className="mt-7 max-w-lg text-sm leading-7 text-white/60">Describe the job. We'll turn it into a clear next step.</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}} className="rounded-3xl bg-[#eee9de] p-5 text-[#20251f] sm:p-8">{sent?<div className="py-12"><Check/><h3 className="mt-5 text-3xl">Quote request received.</h3><p className="mt-2 text-sm opacity-50">Demo success state — connect to CRM/email in production.</p></div>:<><input required placeholder="Name" className="h-14 w-full rounded-xl border border-black/10 bg-transparent px-4"/><input required placeholder="Phone / WhatsApp" className="mt-3 h-14 w-full rounded-xl border border-black/10 bg-transparent px-4"/><select className="mt-3 h-14 w-full rounded-xl border border-black/10 bg-transparent px-4"><option>Home care</option><option>Maintenance</option><option>Commercial</option><option>Emergency</option></select><textarea rows={4} placeholder="Tell us about the job" className="mt-3 w-full rounded-xl border border-black/10 bg-transparent p-4"/><button className="mt-3 h-14 w-full rounded-xl bg-[#20251f] text-[9px] font-bold uppercase tracking-[.16em] text-white">Request quote ↗</button></>}</form></div></section>
 <footer className="px-5 py-10 text-[8px] uppercase tracking-[.17em] opacity-40 sm:px-10">Field & Form / Guwahati + nearby / Concept by Ganlary Labs / Demo website</footer></main>;
}
