"use client";

import { ArrowDownRight, ArrowRight, CalendarDays, Check, Clock3, MapPin, Menu, Phone, Plus, Search, Star, X } from "lucide-react";
import { useState } from "react";
import type { DemoConfig } from "./demoData";

function Img({src,alt="",className=""}:{src:string;alt?:string;className?:string}) {
  return <img src={src} alt={alt} className={`h-full w-full object-cover ${className}`} />;
}
function Kicker({children}:{children:React.ReactNode}) {
  return <div className="text-[9px] font-semibold uppercase tracking-[.2em] opacity-50">{children}</div>;
}
function DemoHeader({config, dark=false}:{config:DemoConfig;dark?:boolean}) {
  const [open,setOpen]=useState(false);
  return <header className={`relative z-50 border-b ${dark?"border-white/10 text-white":"border-black/10"}`}>
    <div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-12">
      <a href="/demos" className="text-[11px] font-bold uppercase tracking-[.2em]">{config.brand}</a>
      <nav className="hidden gap-8 md:flex">{config.nav.map(n=><a key={n} href={`#${n.toLowerCase()}`} className="text-[9px] font-semibold uppercase tracking-[.16em] opacity-55 hover:opacity-100">{n}</a>)}</nav>
      <button className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X size={18}/>:<Menu size={18}/>}</button>
      <a href="#contact" className="hidden rounded-full border px-4 py-2 text-[8px] font-semibold uppercase tracking-[.15em] md:block">Start here ↗</a>
    </div>
    {open&&<div className={`border-t px-5 py-3 md:hidden ${dark?"border-white/10":"border-black/10"}`}>{config.nav.map(n=><a key={n} href={`#${n.toLowerCase()}`} className="block border-b py-4 text-[10px] uppercase tracking-[.16em]">{n}</a>)}</div>}
  </header>
}
function Footer({config,dark=false}:{config:DemoConfig;dark?:boolean}) {
  return <footer className={`border-t px-5 py-12 lg:px-12 ${dark?"border-white/10 text-white":"border-black/10"}`}><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="text-2xl tracking-[-.05em]">{config.brand}</div><p className="mt-3 max-w-md text-[10px] leading-5 opacity-40">{config.footerNote}</p></div><div className="text-[8px] uppercase tracking-[.18em] opacity-35">Concept website / Ganlary Labs / 2026</div></div></footer>
}
function Form({config,label="Send enquiry"}:{config:DemoConfig;label?:string}) {
  const [sent,setSent]=useState(false);
  if(sent)return <div className="rounded-3xl border border-black/10 bg-white/40 p-7"><Check size={18}/><h3 className="mt-4 text-2xl tracking-[-.04em]">You're on the list.</h3><p className="mt-2 text-sm opacity-55">This demonstration flow is ready to connect to a real booking, CRM or enquiry system.</p></div>;
  return <form onSubmit={e=>{e.preventDefault();setSent(true)}} className="grid gap-3">
    <input required placeholder="Your name" className="h-14 rounded-2xl border border-black/10 bg-transparent px-4 text-sm outline-none"/>
    <input required type="email" placeholder="Email address" className="h-14 rounded-2xl border border-black/10 bg-transparent px-4 text-sm outline-none"/>
    <textarea required rows={4} placeholder="Tell us a little more…" className="rounded-2xl border border-black/10 bg-transparent p-4 text-sm outline-none"/>
    <button className="flex h-14 items-center justify-between rounded-2xl bg-black px-5 text-[9px] font-semibold uppercase tracking-[.16em] text-white">{label}<ArrowRight size={15}/></button>
  </form>
}

/* Aster & Ash — magazine-like dining room, menu-first */
export function RestaurantDemo({config}:{config:DemoConfig}) {
 const [menu,setMenu]=useState(0);
 return <main className="bg-[#eee8dc] text-[#241d18]">
  <DemoHeader config={config}/>
  <section className="relative min-h-[92svh] overflow-hidden bg-[#17110e] text-[#f5eee5]">
   <Img src={config.heroImage} className="absolute inset-0 opacity-60"/>
   <div className="absolute inset-0 bg-gradient-to-t from-[#17110e] via-transparent to-[#17110e]/30"/>
   <div className="relative mx-auto flex min-h-[92svh] max-w-[1500px] flex-col justify-between p-6 lg:p-12">
    <div className="flex justify-between text-[8px] uppercase tracking-[.2em] opacity-55"><span>New Delhi</span><span>Open Tue—Sun / 7 PM—Late</span></div>
    <div><Kicker>Aster & Ash / Modern dining house</Kicker><h1 className="mt-5 max-w-6xl font-serif text-[clamp(4.7rem,11vw,11rem)] leading-[.72] tracking-[-.07em]">Dinner worth<br/><i className="text-[#c68a63]">remembering.</i></h1><p className="mt-8 max-w-md text-sm leading-7 text-white/55">{config.heroBody}</p></div>
   </div>
  </section>
  <section className="border-b border-black/10 bg-[#e0d3c2] px-5 py-5 lg:px-12"><div className="mx-auto grid max-w-[1500px] gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-white/35 p-4"><span className="block text-[8px] uppercase tracking-[.15em] opacity-45">Date</span><span className="mt-2 block text-sm">Friday, 24 Oct</span></div><div className="rounded-2xl bg-white/35 p-4"><span className="block text-[8px] uppercase tracking-[.15em] opacity-45">Guests</span><span className="mt-2 block text-sm">2 people</span></div><div className="rounded-2xl bg-white/35 p-4"><span className="block text-[8px] uppercase tracking-[.15em] opacity-45">Time</span><span className="mt-2 block text-sm">8:30 PM</span></div><a href="#contact" className="flex items-center justify-between rounded-2xl bg-[#241d18] p-4 text-[9px] font-semibold uppercase tracking-[.16em] text-white">Check availability <ArrowRight size={14}/></a></div></section>
  <section id="about" className="px-5 py-28 lg:px-12 lg:py-40"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.28fr_1fr]"><Kicker>01 / The kitchen</Kicker><div><h2 className="max-w-6xl font-serif text-[clamp(3.6rem,7vw,8rem)] leading-[.8] tracking-[-.06em]">Seasonal ingredients.<br/><i>Quiet confidence.</i></h2><p className="mt-10 max-w-2xl text-base leading-8 opacity-55">{config.introBody}</p><div className="mt-14 grid grid-cols-2 border-y border-black/10 sm:grid-cols-4">{config.stats.map(s=><div key={s.label} className="border-b border-black/10 p-5 sm:border-b-0 sm:border-r">{s.value}<span className="mt-2 block text-[8px] uppercase tracking-[.15em] opacity-40">{s.label}</span></div>)}</div></div></div></section>
  <section id="services" className="bg-[#241d18] px-5 py-28 text-[#f5eee5] lg:px-12 lg:py-40"><div className="mx-auto max-w-[1500px]"><Kicker>02 / Tonight's menu</Kicker><div className="mt-10 grid gap-16 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">Made for<br/><i className="text-[#c68a63]">the table.</i></h2><p className="mt-8 max-w-sm text-sm leading-7 text-white/45">Choose a tasting journey, order à la carte, or leave the evening to the chef. The menu changes with the season.</p></div><div className="border-t border-white/15">{config.services.map((s,i)=><button key={s.number} onClick={()=>setMenu(i)} className="w-full border-b border-white/15 py-7 text-left"><div className="flex justify-between"><span className="font-serif text-2xl sm:text-4xl">{s.name}</span>{menu===i?<X size={15}/>:<Plus size={15}/>}</div>{menu===i&&<p className="mt-3 max-w-xl text-sm leading-6 text-white/45">{s.description}</p>}</button>)}</div></div></div></section>
  <section id="gallery" className="px-5 py-24 lg:px-12"><div className="mx-auto max-w-[1500px]"><Kicker>03 / At the table</Kicker><div className="mt-10 grid gap-3 sm:grid-cols-12">{config.gallery.map((g,i)=><div key={g} className={`overflow-hidden rounded-[22px] ${i===0?"sm:col-span-7 sm:row-span-2 aspect-[.9]":"sm:col-span-5 aspect-[1.3]"}`}><Img src={g}/></div>)}</div></div></section>
  <section id="contact" className="bg-[#c68a63] px-5 py-28 lg:px-12"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1fr_.65fr]"><div><Kicker>04 / Reservations</Kicker><h2 className="mt-6 max-w-4xl font-serif text-[clamp(4rem,8vw,8rem)] leading-[.76] tracking-[-.06em]">Save your<br/>seat.</h2><p className="mt-8 max-w-lg text-sm leading-7 opacity-65">{config.closingBody}</p></div><Form config={config} label="Request a table"/></div></section>
  <Footer config={config}/>
 </main>
}

/* Northline — healthcare uses treatment pathways, doctor trust and appointment utility */
export function ClinicDemo({config}:{config:DemoConfig}) {
 const [active,setActive]=useState(0);
 return <main className="bg-[#f4f7f4] text-[#123431]">
  <DemoHeader config={config}/>
  <section className="bg-[#dcebe7] px-5 py-8 lg:px-12 lg:py-12"><div className="mx-auto grid max-w-[1500px] gap-8 lg:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col justify-end"><Kicker>Northline Dental / Guwahati</Kicker><h1 className="mt-8 text-[clamp(4rem,9vw,9rem)] font-medium leading-[.78] tracking-[-.08em]">Care that<br/><i className="font-serif font-normal text-[#0f716a]">feels human.</i></h1><p className="mt-8 max-w-lg text-base leading-7 opacity-55">{config.heroBody}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#appointment" className="rounded-full bg-[#0f716a] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em] text-white">Book appointment ↗</a><a href="#services" className="rounded-full border border-[#123431]/15 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em]">Explore treatments</a></div></div><div className="relative min-h-[500px] overflow-hidden rounded-[28px]"><Img src={config.heroImage}/><div className="absolute bottom-4 left-4 rounded-2xl bg-white/85 p-4 backdrop-blur"><div className="flex items-center gap-2 text-[8px] font-semibold uppercase tracking-[.15em]"><Star size={12} fill="currentColor"/> 4.9 patient experience</div><div className="mt-2 text-xs opacity-55">Open today until 8 PM</div></div></div></div></section>
  <section id="about" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>01 / Your care pathway</Kicker><h2 className="mt-6 max-w-5xl text-[clamp(3.4rem,7vw,7rem)] font-medium leading-[.82] tracking-[-.07em]">Know what happens<br/>before you arrive.</h2><div className="mt-16 grid gap-px overflow-hidden rounded-3xl bg-black/10 sm:grid-cols-4">{["Tell us what hurts","Meet your dentist","Understand your options","Leave with a plan"].map((x,i)=><div key={x} className="bg-[#f4f7f4] p-6"><span className="text-[9px] text-[#0f716a]">0{i+1}</span><h3 className="mt-12 text-lg font-medium">{x}</h3><p className="mt-3 text-xs leading-6 opacity-45">{["Quick enquiry, symptoms and preferred time.","A calm consultation with clear explanations.","Treatment options, timing and estimated costs.","Aftercare guidance and a clear follow-up path."][i]}</p></div>)}</div></div></section>
  <section id="services" className="bg-[#18352f] px-5 py-24 text-[#eff5ef] lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>Treatments / choose your path</Kicker><div className="mt-12 grid gap-3 md:grid-cols-2">{config.services.map((s,i)=><button key={s.number} onClick={()=>setActive(i)} className="rounded-3xl border p-7 text-left sm:p-9" style={{borderColor:"rgba(255,255,255,.12)",background:active===i?"rgba(255,255,255,.07)":"transparent"}}><div className="flex justify-between text-[9px] opacity-35">{s.number}<ArrowDownRight size={14}/></div><h3 className="mt-14 text-2xl font-medium sm:text-4xl">{s.name}</h3><p className="mt-4 max-w-md text-sm leading-6 opacity-45">{s.description}</p><span className="mt-8 block text-[8px] font-semibold uppercase tracking-[.16em] text-[#9bc4b6]">Treatment guide →</span></button>)}</div></div></section>
  <section className="px-5 py-24 lg:px-12"><div className="mx-auto grid max-w-[1500px] gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><Kicker>03 / The team</Kicker><h2 className="mt-5 text-[clamp(3rem,6vw,6rem)] font-medium leading-[.84] tracking-[-.07em]">People you can<br/>talk to.</h2><p className="mt-6 max-w-md text-sm leading-7 opacity-50">Every specialist profile answers the practical questions patients have before choosing a provider: focus area, approach, experience and appointment type.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl bg-[#dcebe7] p-6"><div className="aspect-square overflow-hidden rounded-2xl"><Img src={config.gallery[0]}/></div><h3 className="mt-5 text-xl font-medium">Dr. Mira Sen</h3><p className="mt-1 text-[9px] uppercase tracking-[.15em] opacity-45">Cosmetic & restorative</p></div><div className="rounded-3xl bg-[#e9efeb] p-6"><div className="aspect-square overflow-hidden rounded-2xl"><Img src={config.gallery[1]}/></div><h3 className="mt-5 text-xl font-medium">Dr. Arjun Das</h3><p className="mt-1 text-[9px] uppercase tracking-[.15em] opacity-45">Implants & surgery</p></div></div></div></section>
  <section id="appointment" className="bg-[#0f716a] px-5 py-24 text-white lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1fr_.65fr]"><div><Kicker>04 / Appointment</Kicker><h2 className="mt-6 max-w-4xl text-[clamp(3.5rem,7vw,7rem)] font-medium leading-[.8] tracking-[-.07em]">Let's make<br/>your next visit<br/><i className="font-serif font-normal">easier.</i></h2><div className="mt-10 flex gap-6 text-[9px] uppercase tracking-[.15em] opacity-60"><span className="flex items-center gap-2"><Clock3 size={13}/> 30–60 min</span><span className="flex items-center gap-2"><MapPin size={13}/> Guwahati</span></div></div><div className="rounded-3xl bg-white p-5 text-[#123431] sm:p-8"><Form config={config} label="Request appointment"/></div></div></section>
  <Footer config={config}/>
 </main>
}

/* North & Form — search-led real estate, with filters and property facts */
export function RealEstateDemo({config}:{config:DemoConfig}) {
 const [filter,setFilter]=useState("All");
 const filters=["All","Homes","Apartments","Land"];
 return <main className="bg-[#171713] text-[#f0ece2]"><DemoHeader config={config} dark/>
  <section className="relative min-h-[82svh] overflow-hidden"><Img src={config.heroImage} className="absolute inset-0 opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#171713] to-transparent"/><div className="relative mx-auto flex min-h-[82svh] max-w-[1500px] flex-col justify-end px-5 pb-10 lg:px-12 lg:pb-16"><div className="text-[8px] uppercase tracking-[.2em] opacity-50">{config.location}</div><h1 className="mt-5 max-w-6xl text-[clamp(4.5rem,10vw,10rem)] font-medium leading-[.74] tracking-[-.08em]">Places with<br/><i className="font-serif font-normal text-[#c8a66a]">presence.</i></h1></div></section>
  <section className="sticky top-0 z-30 border-y border-white/10 bg-[#171713]/95 px-5 py-4 backdrop-blur lg:px-12"><div className="mx-auto flex max-w-[1500px] items-center gap-2 overflow-x-auto">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className="whitespace-nowrap rounded-full border px-4 py-2 text-[8px] uppercase tracking-[.16em]" style={{borderColor:filter===f?"#c8a66a":"rgba(255,255,255,.12)",color:filter===f?"#c8a66a":"white"}}>{f}</button>)}<button className="ml-auto hidden items-center gap-2 text-[8px] uppercase tracking-[.16em] opacity-50 sm:flex"><Search size={13}/> Filters</button></div></section>
  <section id="properties" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><div className="flex items-end justify-between"><div><Kicker>01 / Curated collection</Kicker><h2 className="mt-5 font-serif text-[clamp(3.2rem,7vw,7rem)] leading-[.8]">Four places<br/>to begin.</h2></div><span className="text-[8px] uppercase tracking-[.18em] opacity-35">{filter} / 04</span></div><div className="mt-14 grid gap-12 sm:grid-cols-2">{config.gallery.map((g,i)=><article key={g}><div className="group relative aspect-[.9] overflow-hidden rounded-[3px]"><Img src={g} className="transition duration-1000 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-black/40 px-3 py-2 text-[8px] uppercase tracking-[.15em] backdrop-blur">For sale</span></div><div className="grid grid-cols-[1fr_auto] gap-4 border-b border-white/10 py-5"><div><div className="text-[8px] uppercase tracking-[.16em] text-[#c8a66a]">North & Form / 0{i+1}</div><h3 className="mt-2 text-2xl">{["Ridge House","The Courtyard","Forest Residence","Hill House"][i]}</h3><p className="mt-2 text-xs opacity-40">4 bed · 3 bath · 3,280 sq ft · Mountain view</p></div><div className="text-right text-lg">₹{["3.8Cr","2.4Cr","4.2Cr","1.95Cr"][i]}</div></div></article>)}</div></div></section>
  <section id="about" className="bg-[#e9e4d8] px-5 py-24 text-[#171713] lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.3fr_1fr]"><Kicker>02 / Our point of view</Kicker><div><h2 className="max-w-6xl font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.8]">The right address<br/><i>changes the day.</i></h2><p className="mt-9 max-w-2xl text-base leading-8 opacity-55">{config.introBody}</p><div className="mt-14 grid grid-cols-2 border-y border-black/10 sm:grid-cols-4">{config.stats.map(s=><div key={s.label} className="border-b border-black/10 p-5 sm:border-b-0 sm:border-r">{s.value}<span className="mt-2 block text-[8px] uppercase tracking-[.15em] opacity-40">{s.label}</span></div>)}</div></div></div></section>
  <section id="gallery" className="px-5 py-24 lg:px-12"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1.2fr_.8fr]"><div className="aspect-[.8] overflow-hidden"><Img src={config.featureImage}/></div><div className="flex flex-col justify-end"><Kicker>03 / Neighbourhood intelligence</Kicker><h2 className="mt-6 text-[clamp(3rem,6vw,6rem)] leading-[.83] tracking-[-.06em]">Don't just<br/>buy the house.<br/><i className="font-serif text-[#c8a66a]">Know the life.</i></h2><p className="mt-7 max-w-md text-sm leading-7 opacity-45">Each listing can expand into a local guide: schools, commute, cafés, parks, medical access, weekend routes and the small details that turn an address into a decision.</p></div></div></section>
  <section id="contact" className="bg-[#c8a66a] px-5 py-24 text-[#171713] lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1fr_.65fr]"><div><Kicker>04 / Private viewing</Kicker><h2 className="mt-6 font-serif text-[clamp(4rem,8vw,8rem)] leading-[.76]">Let's see<br/>the place.</h2><p className="mt-7 max-w-lg text-sm leading-7 opacity-60">Tell us which property caught your eye. We'll arrange the next step around your schedule.</p></div><Form config={config} label="Request viewing"/></div></section><Footer config={config} dark/></main>
}

/* Morrow — visual lookbook + stylist-led booking */
export function SalonDemo({config}:{config:DemoConfig}) {
 const [service,setService]=useState(0);
 return <main className="bg-[#f0e6e1] text-[#302425]"><DemoHeader config={config}/>
  <section className="grid min-h-[88svh] lg:grid-cols-2"><div className="flex flex-col justify-between p-6 lg:p-12"><div><Kicker>Morrow / Beauty house / Bengaluru</Kicker><h1 className="mt-16 max-w-4xl font-serif text-[clamp(5rem,11vw,11rem)] leading-[.68] tracking-[-.07em]">Your ritual,<br/><i className="text-[#9a5d64]">reimagined.</i></h1></div><div className="mt-16 max-w-md"><p className="text-sm leading-7 opacity-55">{config.heroBody}</p><a href="#book" className="mt-7 inline-flex rounded-full bg-[#302425] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em] text-white">Book your visit ↗</a></div></div><div className="relative min-h-[500px]"><Img src={config.heroImage}/><div className="absolute bottom-5 left-5 rounded-2xl bg-[#f0e6e1]/85 p-4 backdrop-blur"><span className="text-[8px] uppercase tracking-[.15em] opacity-45">This season</span><div className="mt-2 text-sm">Soft structure / natural colour</div></div></div></section>
  <section id="about" className="border-y border-black/10 px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>01 / The philosophy</Kicker><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_.65fr]"><h2 className="font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.78] tracking-[-.06em]">Beauty is a feeling<br/>before it is<br/><i className="text-[#9a5d64]">a service.</i></h2><p className="self-end text-base leading-8 opacity-55">{config.introBody}</p></div></div></section>
  <section id="services" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Kicker>02 / The menu</Kicker><h2 className="mt-5 text-[clamp(3.5rem,7vw,7rem)] font-medium leading-[.78] tracking-[-.07em]">Choose your<br/><i className="font-serif font-normal text-[#9a5d64]">ritual.</i></h2></div><p className="max-w-xs text-xs leading-6 opacity-45">Every service includes a consultation. Prices shown are starting points.</p></div><div className="mt-14 border-t border-black/10">{config.services.map((s,i)=><button key={s.number} onClick={()=>setService(i)} className="grid w-full grid-cols-[30px_1fr_auto] gap-4 border-b border-black/10 py-7 text-left sm:grid-cols-[70px_1fr_auto]"><span className="font-mono text-[9px] opacity-35">{s.number}</span><span><strong className="font-serif text-2xl font-normal sm:text-4xl">{s.name}</strong>{service===i&&<p className="mt-3 max-w-xl text-sm leading-6 opacity-50">{s.description}</p>}</span><span className="text-sm opacity-40">{service===i?"—":"+"}</span></button>)}</div></div></section>
  <section id="gallery" className="bg-[#302425] px-5 py-24 text-[#f5ece8] lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>03 / The lookbook</Kicker><div className="mt-10 grid gap-3 sm:grid-cols-3">{config.gallery.map((g,i)=><div key={g} className={i===1?"sm:translate-y-20":""}><div className="aspect-[.78] overflow-hidden"><Img src={g}/></div><div className="mt-4 text-[8px] uppercase tracking-[.17em] opacity-40">Look / 0{i+1}</div></div>)}</div></div></section>
  <section id="book" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.9fr_.7fr]"><div><Kicker>04 / Book an artist</Kicker><h2 className="mt-6 font-serif text-[clamp(4rem,8vw,8rem)] leading-[.75]">Make time<br/>for yourself.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/45 p-5"><span className="text-[8px] uppercase tracking-[.15em] opacity-40">Artist</span><p className="mt-2">Maya / Senior stylist</p></div><div className="rounded-2xl bg-white/45 p-5"><span className="text-[8px] uppercase tracking-[.15em] opacity-40">Next opening</span><p className="mt-2">Thursday / 4:30 PM</p></div></div></div><Form config={config} label="Request appointment"/></div></section><Footer config={config}/></main>
}

/* Northstar — course discovery, curriculum and application */
export function EducationDemo({config}:{config:DemoConfig}) {
 const [tab,setTab]=useState(0);
 return <main className="bg-[#f3f0e8] text-[#1b211e]"><DemoHeader config={config}/>
  <section className="px-5 py-10 lg:px-12 lg:py-16"><div className="mx-auto max-w-[1500px]"><div className="flex justify-between text-[8px] uppercase tracking-[.2em] opacity-40"><span>Northstar Academy</span><span>Admissions / 2026</span></div><div className="mt-16 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><Kicker>Learn / build / launch</Kicker><h1 className="mt-7 max-w-6xl text-[clamp(4rem,10vw,10rem)] font-medium leading-[.75] tracking-[-.08em]">Learn what<br/><i className="font-serif font-normal text-[#315f4a]">moves you forward.</i></h1><p className="mt-8 max-w-xl text-base leading-7 opacity-55">{config.heroBody}</p><div className="mt-8 flex gap-3"><a href="#programs" className="rounded-full bg-[#315f4a] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em] text-white">Find your program ↗</a><a href="#process" className="rounded-full border border-black/10 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em]">How it works</a></div></div><div className="aspect-[.9] overflow-hidden rounded-[28px]"><Img src={config.heroImage}/></div></div></div></section>
  <section id="about" className="bg-[#dfe5da] px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>01 / The Northstar model</Kicker><div className="mt-12 grid gap-px overflow-hidden rounded-3xl bg-black/10 md:grid-cols-3">{[["Learn","Focused curriculum built around useful fundamentals."],["Build","Projects turn concepts into work you can actually show."],["Launch","Mentors help translate the work into your next opportunity."]].map((x,i)=><div key={x[0]} className="bg-[#dfe5da] p-7 lg:p-10"><span className="font-mono text-[9px] text-[#315f4a]">0{i+1}</span><h2 className="mt-20 text-3xl font-medium">{x[0]}</h2><p className="mt-4 max-w-sm text-sm leading-7 opacity-50">{x[1]}</p></div>)}</div></div></section>
  <section id="programs" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>02 / Programs</Kicker><div className="mt-10 grid gap-3 lg:grid-cols-2">{config.services.map((s,i)=><button key={s.number} onClick={()=>setTab(i)} className="rounded-[24px] border border-black/10 p-7 text-left sm:p-9" style={{background:tab===i?"#315f4a":"transparent",color:tab===i?"#f3f0e8":"inherit"}}><div className="flex justify-between"><span className="font-mono text-[9px] opacity-40">{s.number}</span><ArrowDownRight size={15}/></div><h3 className="mt-16 text-3xl font-medium tracking-[-.05em]">{s.name}</h3><p className="mt-4 max-w-lg text-sm leading-7 opacity-50">{s.description}</p><div className="mt-8 flex flex-wrap gap-2 text-[8px] uppercase tracking-[.15em] opacity-50"><span>06 weeks</span><span>•</span><span>Project-led</span><span>•</span><span>Mentor feedback</span></div></button>)}</div></div></section>
  <section id="process" className="bg-[#1b211e] px-5 py-24 text-[#f3f0e8] lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Kicker>03 / A week at Northstar</Kicker><h2 className="mt-6 text-[clamp(3.5rem,7vw,7rem)] leading-[.8] tracking-[-.07em]">You don't<br/>just watch.<br/><i className="font-serif text-[#8fb09c]">You make.</i></h2></div><div className="border-t border-white/10">{["Monday / Learn","Tuesday / Workshop","Wednesday / Build","Thursday / Mentor review","Friday / Ship"].map((x,i)=><div key={x} className="grid grid-cols-[40px_1fr] gap-4 border-b border-white/10 py-6"><span className="font-mono text-[9px] text-[#8fb09c]">0{i+1}</span><div><h3 className="text-xl">{x}</h3><p className="mt-2 text-sm opacity-40">{["New concepts and examples.","Hands-on guided practice.","Independent project work.","Feedback, critique and iteration.","Demo, reflect and publish."][i]}</p></div></div>)}</div></div></section>
  <section id="contact" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1fr_.65fr]"><div><Kicker>04 / Admissions</Kicker><h2 className="mt-6 max-w-4xl text-[clamp(4rem,8vw,8rem)] leading-[.75] tracking-[-.07em]">Build your<br/><i className="font-serif text-[#315f4a]">next chapter.</i></h2><p className="mt-8 max-w-lg text-sm leading-7 opacity-50">{config.closingBody}</p></div><Form config={config} label="Start application"/></div></section><Footer config={config}/></main>
}

/* Field & Form — practical local service, quote-first utility */
export function LocalServiceDemo({config}:{config:DemoConfig}) {
 const [active,setActive]=useState(0);
 return <main className="bg-[#eee9de] text-[#1c201d]"><DemoHeader config={config}/>
  <section className="px-5 py-5 lg:px-8"><div className="mx-auto max-w-[1500px] rounded-[28px] bg-[#252c27] p-6 text-[#f1eee6] lg:p-12"><div className="grid min-h-[76svh] gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div className="flex flex-col justify-end"><Kicker>Field & Form / Guwahati + nearby</Kicker><h1 className="mt-7 max-w-6xl text-[clamp(4.3rem,10vw,10rem)] font-medium leading-[.75] tracking-[-.08em]">Good work,<br/><i className="font-serif font-normal text-[#d29b68]">done properly.</i></h1><p className="mt-8 max-w-lg text-base leading-7 text-white/55">{config.heroBody}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#quote" className="rounded-full bg-[#d29b68] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em] text-[#252c27]">Request a quote ↗</a><a href="#services" className="rounded-full border border-white/15 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.16em]">Services</a></div></div><div className="relative h-full min-h-[400px] overflow-hidden rounded-[22px]"><Img src={config.heroImage}/><div className="absolute bottom-4 left-4 right-4 flex items-center justify-between rounded-2xl bg-black/30 p-4 backdrop-blur"><span className="text-[8px] uppercase tracking-[.15em]">Average response</span><strong className="text-sm">Under 60 minutes</strong></div></div></div></div></section>
  <section className="border-y border-black/10 px-5 py-5 lg:px-12"><div className="mx-auto grid max-w-[1500px] grid-cols-2 gap-5 sm:grid-cols-4">{config.stats.map(s=><div key={s.label}><div className="text-2xl tracking-[-.05em]">{s.value}</div><div className="mt-1 text-[8px] uppercase tracking-[.15em] opacity-40">{s.label}</div></div>)}</div></section>
  <section id="about" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[.25fr_1fr]"><Kicker>01 / The promise</Kicker><div><h2 className="max-w-6xl text-[clamp(3.5rem,7vw,7rem)] font-medium leading-[.8] tracking-[-.07em]">The people you call<br/>when it needs doing<br/><i className="font-serif text-[#b46d32]">right.</i></h2><p className="mt-10 max-w-2xl text-base leading-8 opacity-50">{config.introBody}</p></div></div></section>
  <section id="services" className="bg-[#d9d1c3] px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1500px]"><Kicker>02 / What we do</Kicker><div className="mt-12 grid gap-3 lg:grid-cols-[1fr_1fr]">{config.services.map((s,i)=><button key={s.number} onClick={()=>setActive(i)} className="rounded-3xl bg-[#eee9de] p-7 text-left sm:p-9"><div className="flex justify-between"><span className="font-mono text-[9px] opacity-35">{s.number}</span>{active===i?<Check size={15}/>:<Plus size={15}/>}</div><h3 className="mt-16 text-3xl font-medium tracking-[-.05em]">{s.name}</h3><p className="mt-3 max-w-md text-sm leading-7 opacity-50">{s.description}</p>{active===i&&<div className="mt-7 flex gap-5 text-[8px] uppercase tracking-[.15em] opacity-50"><span>Quote available</span><span>•</span><span>Local team</span></div>}</button>)}</div></div></section>
  <section id="gallery" className="px-5 py-24 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="grid grid-cols-2 gap-3"><div className="aspect-[.8] overflow-hidden rounded-3xl"><Img src={config.gallery[0]}/></div><div className="mt-12 aspect-[.8] overflow-hidden rounded-3xl"><Img src={config.gallery[1]}/></div></div><div className="flex flex-col justify-end"><Kicker>03 / Work we stand behind</Kicker><h2 className="mt-6 text-[clamp(3.2rem,6vw,6rem)] leading-[.82] tracking-[-.07em]">Clear quotes.<br/>Clean work.<br/><i className="font-serif text-[#b46d32]">No drama.</i></h2><p className="mt-7 max-w-lg text-sm leading-7 opacity-50">Showcase real work by service type, explain what changed, and let customers understand the standard before they ask for a quote.</p><div className="mt-8 grid grid-cols-2 gap-3">{["Before / after","Materials","Service area","Care guide"].map(x=><div key={x} className="rounded-2xl border border-black/10 p-4 text-[9px] uppercase tracking-[.15em]">{x}</div>)}</div></div></div></section>
  <section id="quote" className="bg-[#b46d32] px-5 py-24 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-[1fr_.65fr]"><div><Kicker>04 / Get a quote</Kicker><h2 className="mt-6 max-w-4xl text-[clamp(4rem,8vw,8rem)] font-medium leading-[.75] tracking-[-.07em]">Tell us what<br/>needs doing.</h2><p className="mt-8 max-w-lg text-sm leading-7 opacity-60">Describe the job, tell us where you are and we'll turn a vague problem into a clear next step.</p></div><Form config={config} label="Request quote"/></div></section><Footer config={config}/></main>
}
