"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, ChevronDown, Menu, Search, X } from "lucide-react";

const properties = [
  {name:"The Courtyard House",place:"Khanapara · Guwahati",price:"₹3.85 Cr",meta:"4 bed · 4,820 sq ft",img:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1300&q=88"},
  {name:"House No. 17",place:"Six Mile · Guwahati",price:"₹2.40 Cr",meta:"3 bed · 3,160 sq ft",img:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1300&q=88"},
  {name:"The Glass House",place:"Beltola · Guwahati",price:"₹5.10 Cr",meta:"5 bed · 6,400 sq ft",img:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1300&q=88"},
];

export default function RealEstateDemo(){
  const [menu,setMenu]=useState(false); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All homes");
  return <main className="min-h-screen bg-[#e9e6dc] text-[#181a18]">
    <header className="relative z-40 border-b border-[#181a18]/10 bg-[#e9e6dc]"><div className="mx-auto flex h-[76px] max-w-[1500px] items-center justify-between px-5 sm:px-8 lg:px-12"><Link href="/demos" className="text-[8px] uppercase tracking-[.2em] text-black/40">← Demos</Link><div className="absolute left-1/2 -translate-x-1/2 text-center"><div className="font-serif text-xl tracking-[-.03em]">North & Form</div><div className="text-[7px] uppercase tracking-[.25em] text-black/40">Property / Architecture</div></div><button onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="absolute right-4 top-[68px] w-64 border border-black/10 bg-[#e9e6dc] p-5 shadow-xl">{["Homes","Neighbourhoods","Journal","About","Enquire"].map(x=><a key={x} href={"#"+x.toLowerCase().replaceAll(" ","-")} className="block border-b border-black/10 py-4 text-[9px] uppercase tracking-[.18em]">{x}</a>)}</nav>}</header>

    <section className="mx-auto max-w-[1500px] px-3 pt-3 sm:px-5"><div className="relative min-h-[720px] overflow-hidden bg-[#242621] sm:min-h-[820px]"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=90" className="absolute inset-0 h-full w-full object-cover" alt="Architectural home"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-black/15"/><div className="absolute left-5 top-5 flex items-center gap-3 text-[8px] uppercase tracking-[.2em] text-white/60 sm:left-8 sm:top-8"><span className="h-px w-7 bg-[#cbbd96]"/> Curated property / 2026</div><div className="absolute inset-x-5 bottom-7 sm:left-8 sm:bottom-9"><div className="max-w-4xl font-serif text-[clamp(4.2rem,10vw,9rem)] leading-[.77] tracking-[-.07em] text-white">Space with<br/><i className="text-[#cbbd96]">intention.</i></div><p className="mt-7 max-w-lg text-sm leading-7 text-white/55">North & Form represents homes where architecture, material and place are worth talking about.</p></div></div></section>

    <section className="mx-auto max-w-[1500px] px-5 py-16 sm:px-8 md:py-24 lg:px-12"><div className="grid gap-5 border border-black/15 p-4 sm:grid-cols-[1.4fr_1fr_1fr_auto] sm:items-end sm:p-6"><label><span className="block text-[8px] uppercase tracking-[.18em] text-black/40">Search</span><div className="mt-3 flex items-center gap-2 border-b border-black/20 pb-3"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="City, neighbourhood or property" className="w-full bg-transparent text-sm outline-none"/></div></label><label><span className="block text-[8px] uppercase tracking-[.18em] text-black/40">Collection</span><select value={filter} onChange={e=>setFilter(e.target.value)} className="mt-3 w-full border-b border-black/20 bg-transparent pb-3 text-sm outline-none"><option>All homes</option><option>New build</option><option>Heritage</option><option>Private sale</option></select></label><div><span className="block text-[8px] uppercase tracking-[.18em] text-black/40">Bedrooms</span><div className="mt-3 border-b border-black/20 pb-3 text-sm">Any</div></div><button className="bg-[#181a18] px-6 py-4 text-[9px] font-semibold uppercase tracking-[.18em] text-white">Search homes</button></div></section>

    <section id="homes" className="bg-[#181a18] px-5 py-24 text-[#e9e6dc] sm:px-8 md:py-32 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="flex items-end justify-between gap-8"><div><span className="text-[8px] uppercase tracking-[.25em] text-[#cbbd96]">01 / The collection</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Selected<br/><i>homes.</i></h2></div><span className="hidden text-[8px] uppercase tracking-[.18em] text-white/30 sm:block">03 residences</span></div><div className="mt-16 grid gap-10 md:grid-cols-2 lg:grid-cols-3">{properties.map((p,i)=><article key={p.name} className={i===0?"md:col-span-2 lg:col-span-2":""}><div className={"group relative overflow-hidden "+(i===0?"aspect-[1.5]":"aspect-[.82]")}><img src={p.img} alt={p.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><div className="absolute inset-x-5 bottom-5 flex items-end justify-between gap-4 text-white"><div><span className="text-[8px] uppercase tracking-[.18em] text-white/55">{p.place}</span><h3 className="mt-2 font-serif text-3xl leading-none">{p.name}</h3></div><span className="text-sm text-[#cbbd96]">{p.price}</span></div></div><div className="flex justify-between border-b border-white/10 py-4 text-[8px] uppercase tracking-[.16em] text-white/35"><span>{p.meta}</span><a href="#enquire" className="text-white/60">View property ↗</a></div></article>)}</div></div></section>

    <section id="neighbourhoods" className="grid lg:grid-cols-[.9fr_1.1fr]"><div className="bg-[#cbbd96] p-8 sm:p-12 lg:p-20"><span className="text-[8px] uppercase tracking-[.24em] text-black/45">02 / Place matters</span><h2 className="mt-10 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Buy the<br/><i>neighbourhood.</i></h2><p className="mt-10 max-w-md text-sm leading-7 text-black/55">From quiet lanes in the hills to the energy of the city edge, we document the context around every home — schools, coffee, commute, light and landscape.</p><a href="#" className="mt-8 inline-flex items-center gap-2 border-b border-black/30 pb-2 text-[9px] font-semibold uppercase tracking-[.18em]">Explore neighbourhoods <ArrowUpRight size={13}/></a></div><div className="min-h-[520px] bg-cover bg-center" style={{backgroundImage:"url(https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=88)"}}/></section>

    <section className="mx-auto max-w-[1500px] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="grid gap-12 lg:grid-cols-[1fr_.7fr]"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">03 / How we work</span><h2 className="mt-5 max-w-3xl font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Less listing.<br/><i>More looking.</i></h2></div><div className="space-y-7 border-t border-black/15 pt-5">{["Private viewings","Architecture-led curation","Local market intelligence","Quiet, considered negotiation"].map((x,i)=><div key={x} className="flex gap-5 border-b border-black/10 pb-7"><span className="text-[8px] text-black/35">0{i+1}</span><span className="font-serif text-2xl">{x}</span></div>)}</div></div></section>

    <section id="enquire" className="bg-[#dedbd0] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="grid gap-12 lg:grid-cols-[1fr_.75fr]"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">04 / Private enquiry</span><h2 className="mt-5 max-w-3xl font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Tell us what<br/><i>you&apos;re looking for.</i></h2></div><div className="border border-black/15 bg-[#e9e6dc] p-6 sm:p-8"><div className="grid gap-4"><input placeholder="Name" className="border-b border-black/15 bg-transparent py-4 text-sm outline-none"/><input placeholder="Email or phone" className="border-b border-black/15 bg-transparent py-4 text-sm outline-none"/><textarea placeholder="Tell us about the home..." rows={4} className="resize-none border-b border-black/15 bg-transparent py-4 text-sm outline-none"/><button className="mt-3 flex items-center justify-between bg-[#181a18] px-5 py-4 text-[9px] font-semibold uppercase tracking-[.18em] text-white">Request a private viewing <ArrowUpRight size={15}/></button></div></div></div></div></section>

    <footer className="bg-[#181a18] px-5 py-10 text-[#e9e6dc] sm:px-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-8 border-b border-white/10 pb-8 md:flex-row"><div className="font-serif text-3xl">North & Form</div><div className="flex gap-6 text-[8px] uppercase tracking-[.17em] text-white/40"><a href="#homes">Homes</a><a href="#neighbourhoods">Neighbourhoods</a><a href="#enquire">Enquire</a><Link href="/demos">Demos</Link></div></div><div className="pt-5 text-[8px] uppercase tracking-[.17em] text-white/20">Fictional property concept · Ganlary Labs</div></div></footer>
  </main>
}
