"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Calendar, Menu, X } from "lucide-react";

const services = [
  ["CUT / 01","The Morrow Cut","A tailored shape, finished with movement and restraint.","₹1,800"],
  ["COLOUR / 02","Soft Dimension","Hand-painted colour designed to grow out beautifully.","₹4,500"],
  ["RITUAL / 03","The Full Reset","Cut, colour gloss, scalp ritual and finish.","₹6,800"],
  ["SKIN / 04","Studio Facial","A 60-minute skin ritual built around your skin today.","₹2,600"],
];

export default function SalonDemo(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState(0);
 return <main className="min-h-screen bg-[#e9ddd8] text-[#2a211f]">
  <header className="relative z-40 border-b border-[#2a211f]/10"><div className="mx-auto flex h-[76px] max-w-[1480px] items-center justify-between px-5 sm:px-8 lg:px-12"><Link href="/demos" className="text-[8px] uppercase tracking-[.2em] text-black/40">← Demos</Link><div className="absolute left-1/2 -translate-x-1/2 text-center"><div className="font-serif text-2xl italic">Morrow</div><div className="text-[7px] uppercase tracking-[.28em] text-black/40">Hair · Skin · Studio</div></div><button onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="absolute right-4 top-[68px] w-64 border border-black/10 bg-[#e9ddd8] p-5 shadow-xl">{["Services","Artists","Studio","Journal","Book"].map(x=><a key={x} href={"#"+x.toLowerCase()} className="block border-b border-black/10 py-4 text-[9px] uppercase tracking-[.18em]">{x}</a>)}</nav>}</header>

  <section className="mx-auto grid max-w-[1480px] gap-3 px-3 py-3 sm:px-5 lg:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-[700px] overflow-hidden bg-[#3a2d29]"><img src="https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1300&q=90" alt="Morrow beauty editorial" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#1e1715]/65 to-transparent"/><div className="absolute left-5 top-5 text-[8px] uppercase tracking-[.2em] text-white/60">01 / Morrow studio</div><div className="absolute inset-x-5 bottom-6 font-serif text-[clamp(4.5rem,10vw,8rem)] leading-[.76] tracking-[-.07em] text-white">Beauty<br/><i className="text-[#e6b9a8]">with intent.</i></div></div><div className="flex min-h-[700px] flex-col justify-between bg-[#f0e7e2] p-6 sm:p-10 lg:p-14"><div><div className="text-[8px] uppercase tracking-[.22em] text-black/35">A quieter kind of luxury</div><p className="mt-20 max-w-xl font-serif text-[clamp(2.1rem,4vw,4rem)] leading-[.95] tracking-[-.05em]">Hair, skin and rituals designed around <i>you</i> — not the trend cycle.</p></div><div className="border-t border-black/15 pt-5"><div className="flex items-center justify-between"><span className="text-[8px] uppercase tracking-[.18em] text-black/45">Book your studio time</span><Calendar size={16}/></div><button className="mt-5 flex w-full items-center justify-between bg-[#2a211f] px-5 py-4 text-[9px] font-semibold uppercase tracking-[.18em] text-white">Choose a service <ArrowUpRight size={14}/></button></div></div></section>

  <div className="overflow-hidden border-y border-[#2a211f]/15 bg-[#c99888] py-3"><div className="flex min-w-max gap-12 px-5 text-[8px] font-semibold uppercase tracking-[.27em]"><span>Cut / Colour / Skin</span><span>Private studio</span><span>Appointments only</span><span>Slow beauty</span><span>Cut / Colour / Skin</span></div></div>

  <section id="services" className="mx-auto max-w-[1480px] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="grid gap-14 lg:grid-cols-[.65fr_1.35fr]"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">02 / The menu</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Choose<br/><i>your ritual.</i></h2><p className="mt-8 max-w-sm text-sm leading-7 text-black/50">Nothing is rushed. Every appointment begins with a consultation and ends with a finish you can actually recreate at home.</p></div><div className="border-t border-black/15">{services.map(([cat,name,desc,price],i)=><button key={name} onClick={()=>setActive(i)} className={"block w-full border-b border-black/15 py-7 text-left transition "+(active===i?"bg-[#e1cec7]":"")}><div className="grid gap-4 sm:grid-cols-[120px_1fr_auto]"><span className="text-[8px] tracking-[.18em] text-black/35">{cat}</span><div><h3 className="font-serif text-2xl sm:text-3xl">{name}</h3><p className="mt-2 max-w-md text-xs leading-6 text-black/45">{desc}</p></div><span className="text-sm">{price}</span></div></button>)}</div></div></section>

  <section id="artists" className="bg-[#2a211f] px-5 py-24 text-[#f0e7e2] sm:px-8 md:py-32 lg:px-12"><div className="mx-auto max-w-[1480px]"><div className="grid gap-10 md:grid-cols-[1fr_auto] md:items-end"><div><span className="text-[8px] uppercase tracking-[.24em] text-[#e6b9a8]">03 / The artists</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Good hands<br/><i>matter.</i></h2></div><p className="max-w-sm text-sm leading-7 text-white/45">A small team with different points of view — brought together by precision, restraint and a love of good hair.</p></div><div className="mt-16 grid gap-3 sm:grid-cols-3"><div className="relative aspect-[.72] overflow-hidden"><img src="https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=85" className="h-full w-full object-cover" alt="Morrow artist"/><div className="absolute inset-x-4 bottom-4"><div className="font-serif text-2xl">Maya</div><div className="text-[8px] uppercase tracking-[.15em] text-white/50">Colour · Texture</div></div></div><div className="relative aspect-[.72] overflow-hidden"><img src="https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85" className="h-full w-full object-cover" alt="Morrow artist"/><div className="absolute inset-x-4 bottom-4"><div className="font-serif text-2xl">Anya</div><div className="text-[8px] uppercase tracking-[.15em] text-white/50">Cut · Shape</div></div></div><div className="relative aspect-[.72] overflow-hidden"><img src="https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=85" className="h-full w-full object-cover" alt="Morrow artist"/><div className="absolute inset-x-4 bottom-4"><div className="font-serif text-2xl">Rey</div><div className="text-[8px] uppercase tracking-[.15em] text-white/50">Skin · Ritual</div></div></div></div></div></section>

  <section id="studio" className="grid lg:grid-cols-2"><div className="min-h-[560px] bg-cover bg-center" style={{backgroundImage:"url(https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1500&q=88)"}}/><div className="bg-[#d3a99d] p-8 sm:p-12 lg:p-20"><span className="text-[8px] uppercase tracking-[.24em] text-black/40">04 / The studio</span><h2 className="mt-10 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">A room<br/><i>to exhale.</i></h2><p className="mt-10 max-w-md text-sm leading-7 text-black/55">Eight chairs. One private treatment room. Good coffee. No loud music. The studio is intentionally small so the experience never feels crowded.</p><div className="mt-10 grid grid-cols-2 gap-5 border-t border-black/15 pt-5 text-[8px] uppercase tracking-[.17em] text-black/45"><span>8 chairs</span><span>1 private room</span><span>Tue — Sat</span><span>Appointments only</span></div></div></section>

  <footer className="bg-[#f0e7e2] px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1480px]"><div className="flex flex-col justify-between gap-8 border-b border-black/10 pb-9 md:flex-row"><div><div className="font-serif text-4xl italic">Morrow</div><div className="mt-2 text-[7px] uppercase tracking-[.24em] text-black/35">Hair · Skin · Studio</div></div><div className="flex flex-wrap gap-5 text-[8px] uppercase tracking-[.17em] text-black/45"><a href="#services">Services</a><a href="#artists">Artists</a><a href="#studio">Studio</a><Link href="/demos">All demos</Link></div></div><div className="pt-5 text-[8px] uppercase tracking-[.17em] text-black/25">Fictional concept · Ganlary Labs</div></div></footer>
 </main>
}
