"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, ChevronDown, Menu, X } from "lucide-react";

const programs = [
 ["01","Product Engineering","Build and ship software with product-minded engineers.","16 weeks"],
 ["02","AI Systems","Learn how intelligent systems move from prototype to production.","12 weeks"],
 ["03","Data & Decision","Turn messy information into useful decisions and clear stories.","10 weeks"],
];

export default function EducationDemo(){
 const [menu,setMenu]=useState(false); const [open,setOpen]=useState(0);
 return <main className="min-h-screen bg-[#e9e8df] text-[#15261f]">
  <header className="border-b border-[#15261f]/10"><div className="mx-auto flex h-[76px] max-w-[1480px] items-center justify-between px-5 sm:px-8 lg:px-12"><Link href="/demos" className="text-[8px] uppercase tracking-[.2em] text-black/40">← Demos</Link><div className="absolute left-1/2 -translate-x-1/2 text-center"><div className="font-serif text-xl">Northstar</div><div className="text-[7px] uppercase tracking-[.28em] text-black/40">Academy</div></div><button onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="absolute right-4 top-[68px] z-30 w-64 border border-black/10 bg-[#e9e8df] p-5 shadow-xl">{["Programs","Method","Mentors","Student work","Apply"].map(x=><a key={x} href={"#"+x.toLowerCase().replaceAll(" ","-")} className="block border-b border-black/10 py-4 text-[9px] uppercase tracking-[.18em]">{x}</a>)}</nav>}</header>

  <section className="mx-auto max-w-[1480px] px-5 py-8 sm:px-8 md:py-14 lg:px-12"><div className="grid gap-3 lg:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[620px] overflow-hidden bg-[#1c352c] p-6 text-[#e9e8df] sm:min-h-[740px] sm:p-10"><div className="absolute right-0 top-0 h-64 w-64 rounded-full bg-[#c9ad69]/20 blur-3xl"/><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between text-[8px] uppercase tracking-[.2em] text-white/45"><span>Independent learning</span><span>2026 / 27</span></div><div><h1 className="max-w-5xl font-serif text-[clamp(4rem,10vw,9rem)] leading-[.76] tracking-[-.07em]">Learn by<br/><i className="text-[#d6bf86]">building.</i></h1><p className="mt-8 max-w-lg text-sm leading-7 text-white/50">Northstar is a project-led academy for people who want to move from consuming knowledge to making useful things.</p></div></div></div><div className="flex flex-col justify-between bg-[#d6d5c8] p-6 sm:p-10"><div><span className="text-[8px] uppercase tracking-[.2em] text-black/40">01 / The premise</span><p className="mt-20 max-w-md font-serif text-[clamp(2rem,4vw,3.8rem)] leading-[.96] tracking-[-.04em]">You don&apos;t need another course. You need a <i>reason to build.</i></p></div><div className="mt-14 border-t border-black/15 pt-6"><div className="grid grid-cols-2 gap-5"><div><span className="font-serif text-4xl">7</span><p className="mt-1 text-[8px] uppercase tracking-[.15em] text-black/40">Weeks to first project</p></div><div><span className="font-serif text-4xl">1:1</span><p className="mt-1 text-[8px] uppercase tracking-[.15em] text-black/40">Mentor reviews</p></div></div><a href="#apply" className="mt-7 flex items-center justify-between bg-[#15261f] px-5 py-4 text-[9px] font-semibold uppercase tracking-[.18em] text-white">Explore the next cohort <ArrowRight size={15}/></a></div></div></div></section>

  <div className="border-y border-[#15261f]/10 bg-[#c9ad69] py-3"><div className="flex min-w-max gap-12 px-5 text-[8px] font-semibold uppercase tracking-[.26em]"><span>Project-led</span><span>Small cohorts</span><span>Working mentors</span><span>Career-ready work</span><span>Project-led</span></div></div>

  <section id="programs" className="mx-auto max-w-[1480px] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">02 / Programs</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Pick a<br/><i>direction.</i></h2><p className="mt-8 max-w-sm text-sm leading-7 text-black/50">Every program ends with something you can show: a product, a system, a case study or a body of work.</p></div><div className="border-t border-black/15">{programs.map(([n,name,desc,duration],i)=><div key={name} className="border-b border-black/15"><button onClick={()=>setOpen(open===i?-1:i)} className="flex w-full items-center gap-5 py-7 text-left"><span className="text-[8px] tracking-[.2em] text-black/35">{n}</span><span className="flex-1 font-serif text-2xl sm:text-3xl">{name}</span><span className="hidden text-[8px] uppercase tracking-[.16em] text-black/35 sm:block">{duration}</span><ChevronDown size={16} className={open===i?"":"-rotate-90"}/></button>{open===i&&<div className="grid gap-5 pb-7 pl-7 sm:grid-cols-[1fr_auto]"><p className="max-w-lg text-sm leading-7 text-black/50">{desc}</p><a href="#apply" className="text-[8px] font-semibold uppercase tracking-[.18em] underline underline-offset-4">See curriculum ↗</a></div>}</div>)}</div></div></section>

  <section id="method" className="bg-[#15261f] px-5 py-24 text-[#e9e8df] sm:px-8 md:py-32 lg:px-12"><div className="mx-auto max-w-[1480px]"><div className="grid gap-12 lg:grid-cols-[1fr_.8fr]"><div><span className="text-[8px] uppercase tracking-[.24em] text-[#c9ad69]">03 / The method</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Less theory.<br/><i>More reps.</i></h2></div><div className="space-y-7 border-t border-white/15 pt-5">{["Learn the mental model","Build with constraints","Get reviewed by someone working","Ship, document, reflect"].map((x,i)=><div key={x} className="flex gap-5 border-b border-white/10 pb-7"><span className="text-[8px] text-white/30">0{i+1}</span><span className="font-serif text-2xl">{x}</span></div>)}</div></div><div className="mt-16 grid gap-3 md:grid-cols-3"><div className="aspect-square overflow-hidden"><img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1000&q=85" className="h-full w-full object-cover" alt="Students learning"/></div><div className="flex aspect-square flex-col justify-between bg-[#d6d5c8] p-7 text-[#15261f]"><span className="text-[8px] uppercase tracking-[.18em] text-black/40">A different classroom</span><p className="font-serif text-3xl leading-[.95]">The project is the syllabus.</p><span className="text-[8px] uppercase tracking-[.15em] text-black/40">Build / review / ship</span></div><div className="aspect-square overflow-hidden"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85" className="h-full w-full object-cover" alt="Mentor session"/></div></div></div></section>

  <section id="mentors" className="mx-auto max-w-[1480px] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">04 / Mentors</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">People who<br/><i>still build.</i></h2></div><p className="max-w-sm text-sm leading-7 text-black/50">Mentors are practitioners first. They review work, challenge assumptions and help you make the next decision.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-3"><div className="border border-black/10 p-5"><div className="aspect-[.9] overflow-hidden"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=900&q=85" className="h-full w-full object-cover" alt="Mentor"/></div><div className="mt-5 font-serif text-2xl">Rohan Sen</div><div className="mt-1 text-[8px] uppercase tracking-[.15em] text-black/40">Product engineering</div></div><div className="border border-black/10 p-5"><div className="aspect-[.9] overflow-hidden"><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=85" className="h-full w-full object-cover" alt="Mentor"/></div><div className="mt-5 font-serif text-2xl">Nadia Kapoor</div><div className="mt-1 text-[8px] uppercase tracking-[.15em] text-black/40">AI systems</div></div><div className="border border-black/10 p-5"><div className="aspect-[.9] overflow-hidden"><img src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85" className="h-full w-full object-cover" alt="Mentor"/></div><div className="mt-5 font-serif text-2xl">Arun Bose</div><div className="mt-1 text-[8px] uppercase tracking-[.15em] text-black/40">Data & product</div></div></div></section>

  <section id="apply" className="bg-[#c9ad69] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="mx-auto max-w-[1480px]"><div className="grid gap-12 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/45">05 / Applications</span><h2 className="mt-5 max-w-3xl font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Build something<br/><i>worth showing.</i></h2></div><div className="bg-[#e9e8df] p-6 sm:p-8"><input placeholder="Your name" className="w-full border-b border-black/15 bg-transparent py-4 text-sm outline-none"/><input placeholder="Email" className="mt-2 w-full border-b border-black/15 bg-transparent py-4 text-sm outline-none"/><select className="mt-2 w-full border-b border-black/15 bg-transparent py-4 text-sm outline-none"><option>Which program?</option><option>Product Engineering</option><option>AI Systems</option><option>Data & Decision</option></select><button className="mt-7 flex w-full items-center justify-between bg-[#15261f] px-5 py-4 text-[9px] font-semibold uppercase tracking-[.18em] text-white">Start an application <ArrowUpRight size={15}/></button></div></div></div></section>

  <footer className="bg-[#15261f] px-5 py-10 text-[#e9e8df] sm:px-8 lg:px-12"><div className="mx-auto max-w-[1480px]"><div className="flex flex-col justify-between gap-8 md:flex-row"><div><div className="font-serif text-3xl">Northstar</div><div className="mt-1 text-[7px] uppercase tracking-[.25em] text-white/35">Academy</div></div><div className="flex flex-wrap gap-5 text-[8px] uppercase tracking-[.17em] text-white/40"><a href="#programs">Programs</a><a href="#method">Method</a><a href="#mentors">Mentors</a><a href="#apply">Apply</a><Link href="/demos">All demos</Link></div></div><div className="mt-8 border-t border-white/10 pt-5 text-[8px] text-white/20">Fictional education concept · Ganlary Labs</div></div></footer>
 </main>
}
