"use client";

import { useState } from "react";
import { ArrowUpRight, CalendarDays, ChevronDown, Menu, Users, X } from "lucide-react";
import { motion } from "framer-motion";
import { bookingOptions, dining, experiences, galleryImages, hillview, rooms } from "./data";

const hero = hillview.heroImage;

export default function HotelExperience() {
  const [menu, setMenu] = useState(false);
  const [room, setRoom] = useState(0);
  const [guests, setGuests] = useState("2 Adults");
  const [submitted, setSubmitted] = useState(false);

  return (
    <main className="overflow-x-hidden bg-[#f3efe6] text-[#18221d]">
      <header className="absolute inset-x-0 top-0 z-50 text-white">
        <div className="mx-auto flex max-w-[1560px] items-center justify-between px-5 py-5 sm:px-8 lg:px-12 lg:py-7">
          <a href="#top" className="flex items-center gap-3">
            <span className="flex h-9 w-9 items-center justify-center border border-white/40 text-[9px] font-semibold tracking-[.18em]">TH</span>
            <span className="hidden text-[10px] font-semibold uppercase tracking-[.2em] sm:block">The Hillview</span>
          </a>
          <nav className="hidden items-center gap-7 text-[10px] font-semibold uppercase tracking-[.14em] lg:flex">
            <a href="#rooms">Rooms</a><a href="#dining">Dining</a><a href="#experiences">Experiences</a><a href="#gallery">Gallery</a><a href="#location">Location</a>
          </nav>
          <div className="flex items-center gap-2">
            <a href="#booking" className="hidden bg-[#e6d8bf] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.15em] text-[#18221d] sm:block">Book your stay ↗</a>
            <button onClick={() => setMenu(!menu)} className="flex h-10 w-10 items-center justify-center border border-white/35 bg-black/10 backdrop-blur-md lg:hidden" aria-label="Menu">
              {menu ? <X size={17} /> : <Menu size={17} />}
            </button>
          </div>
        </div>
        <div className={`fixed inset-0 bg-[#14251e] px-6 pt-24 transition-opacity duration-500 lg:hidden ${menu ? "pointer-events-auto opacity-100" : "pointer-events-none opacity-0"}`}>
          <div className="border-b border-white/10 pb-6"><div className="text-[9px] uppercase tracking-[.2em] text-[#c8aa7c]">Boutique mountain retreat</div><div className="mt-2 font-serif text-3xl">The Hillview</div></div>
          {["Rooms","Dining","Experiences","Gallery","Location"].map((x) => <a key={x} href={"#"+x.toLowerCase()} onClick={() => setMenu(false)} className="flex border-b border-white/10 py-5 text-2xl">{x}<ArrowUpRight className="ml-auto text-[#c8aa7c]" size={17}/></a>)}
        </div>
      </header>

      <section id="top" className="relative min-h-[760px] overflow-hidden bg-[#14251e] text-white sm:min-h-[850px] lg:min-h-[900px]">
        <img src={hero} alt="The Hillview" className="absolute inset-0 h-full w-full object-cover"/>
        <div className="absolute inset-0 bg-[#0b1711]/35"/>
        <div className="absolute inset-0 bg-gradient-to-r from-[#07110c]/80 via-[#07110c]/35 to-transparent"/>
        <div className="absolute inset-0 bg-gradient-to-t from-[#0f1a14] via-transparent to-black/20"/>
        <div className="relative mx-auto flex min-h-[760px] max-w-[1560px] flex-col justify-end px-5 pb-5 pt-32 sm:min-h-[850px] sm:px-8 sm:pb-8 lg:min-h-[900px] lg:px-12">
          <motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="max-w-5xl">
            <div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#d7c19c]"><span className="h-px w-7 bg-[#c8aa7c]"/>{hillview.category} / {hillview.location}</div>
            <h1 className="mt-6 font-serif text-[clamp(4rem,9vw,9rem)] leading-[.82] tracking-[-.055em]">A more<br/><em className="font-normal text-[#e5d4b6]">considered escape.</em></h1>
            <p className="mt-7 max-w-lg text-[13px] leading-6 text-white/70 sm:text-[15px] sm:leading-7">{hillview.description}</p>
          </motion.div>

          <div id="booking" className="relative z-10 mt-10 max-w-6xl border border-white/20 bg-[#17231e]/95 shadow-2xl backdrop-blur-xl">
            <div className="grid md:grid-cols-[1fr_1fr_.75fr_auto]">
              <label className="border-b border-white/10 p-5 md:border-b-0 md:border-r"><span className="mb-3 flex items-center gap-2 text-[8px] uppercase tracking-[.2em] text-white/35"><CalendarDays size={13} className="text-[#c8aa7c]"/> Check in</span><input type="date" defaultValue="2026-10-12" className="w-full bg-transparent text-sm text-white outline-none [color-scheme:dark]"/></label>
              <label className="border-b border-white/10 p-5 md:border-b-0 md:border-r"><span className="mb-3 flex items-center gap-2 text-[8px] uppercase tracking-[.2em] text-white/35"><CalendarDays size={13} className="text-[#c8aa7c]"/> Check out</span><input type="date" defaultValue="2026-10-15" className="w-full bg-transparent text-sm text-white outline-none [color-scheme:dark]"/></label>
              <label className="border-b border-white/10 p-5 md:border-b-0 md:border-r"><span className="mb-3 flex items-center gap-2 text-[8px] uppercase tracking-[.2em] text-white/35"><Users size={13} className="text-[#c8aa7c]"/> Guests</span><span className="relative block"><select value={guests} onChange={(e)=>setGuests(e.target.value)} className="w-full appearance-none bg-transparent text-sm text-white outline-none">{bookingOptions.guestOptions.map(x=><option key={x} className="bg-[#17231e]">{x}</option>)}</select><ChevronDown size={13} className="pointer-events-none absolute right-0 top-1/2 -translate-y-1/2 text-white/30"/></span></label>
              <a href="#rooms" className="flex min-h-20 items-center justify-center bg-[#e6d8bf] px-7 text-[9px] font-semibold uppercase tracking-[.15em] text-[#18221d] hover:bg-white">Check availability ↗</a>
            </div>
          </div>
          <div className="mt-6 flex justify-between border-t border-white/15 pt-5 text-[8px] uppercase tracking-[.18em] text-white/45"><span>Arunachal Pradesh / 4,900 ft</span><a href="#rooms" className="text-white/75">Explore rooms ↓</a></div>
        </div>
      </section>

      <section className="bg-[#f3efe6] px-5 py-20 sm:px-8 md:py-28 lg:px-12 lg:py-36">
        <div className="mx-auto max-w-[1560px]">
          <div className="grid gap-12 lg:grid-cols-[.28fr_.72fr] lg:gap-20">
            <div><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#536c5d]"><span className="h-px w-7 bg-[#536c5d]"/>The property / 01</div><p className="mt-7 max-w-[210px] text-[9px] uppercase leading-5 tracking-[.12em] text-black/35">A boutique mountain retreat shaped around quiet mornings, warm rooms, local food and the landscape outside.</p></div>
            <div><h2 className="font-serif text-[clamp(3.2rem,7vw,7rem)] leading-[.86] tracking-[-.055em]">Stay somewhere<br/><em className="font-normal text-[#536c5d]">that asks less of you.</em></h2><div className="mt-9 grid gap-8 border-t border-black/10 pt-7 md:grid-cols-[1fr_.55fr]"><p className="text-[14px] leading-7 text-black/55 sm:text-[16px] sm:leading-8">The Hillview is a small mountain retreat designed around the simplest luxury: space to slow down. Spend the morning on your balcony, follow a forest trail after breakfast, and return to a room that feels warm when the hills turn blue.</p><div className="border-l border-black/10 pl-6 text-[10px] text-black/45"><div className="uppercase tracking-[.18em] text-[#536c5d]">At a glance</div><div className="mt-4 space-y-3"><div className="flex justify-between border-b border-black/10 pb-3"><span>Rooms</span><span>03</span></div><div className="flex justify-between border-b border-black/10 pb-3"><span>Elevation</span><span>4,900 ft</span></div><div className="flex justify-between"><span>Setting</span><span>Private hills</span></div></div></div></div></div>
          </div>
          <div className="relative mt-14 aspect-[4/3] overflow-hidden sm:mt-20 sm:aspect-[16/8]"><img src="https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=2400&q=90" alt="Mountain cabin" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent"/><div className="absolute bottom-5 left-5 text-white sm:bottom-8 sm:left-8"><div className="text-[8px] uppercase tracking-[.2em] text-white/60">The Hillview</div><div className="mt-2 font-serif text-2xl sm:text-4xl">Your mountain stay starts here.</div></div></div>
        </div>
      </section>

      <section id="rooms" className="bg-[#e5ded0] px-5 py-20 sm:px-8 md:py-28 lg:px-12 lg:py-36">
        <div className="mx-auto max-w-[1560px]"><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#536c5d]"><span className="h-px w-7 bg-[#536c5d]"/>Rooms / 02</div><div className="mt-7 grid gap-8 lg:grid-cols-[.7fr_.3fr] lg:items-end"><h2 className="font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.82] tracking-[-.06em]">Rooms made<br/><em className="font-normal text-[#536c5d]">for staying.</em></h2><p className="max-w-sm text-[13px] leading-6 text-black/50">Three spaces, each with its own rhythm. Choose a room for two, a generous suite, or the privacy of your own cabin.</p></div>
          <div className="mt-12 grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
            <div className="relative aspect-[4/5] overflow-hidden bg-black"><img src={rooms[room].image} alt={rooms[room].name} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute inset-x-5 bottom-5 text-white sm:inset-x-7 sm:bottom-7"><div className="flex justify-between text-[9px] uppercase tracking-[.2em] text-[#d7c19c]"><span>{rooms[room].number} / {rooms[room].type}</span><span>{rooms[room].price} / night</span></div><h3 className="mt-3 font-serif text-4xl sm:text-6xl">{rooms[room].name}</h3><p className="mt-3 max-w-md text-[12px] leading-5 text-white/60">{rooms[room].description}</p></div></div>
            <div className="flex flex-col"><div className="border-y border-black/10">{rooms.map((item,i)=><button key={item.name} onClick={()=>setRoom(i)} className="flex w-full items-center gap-4 border-b border-black/10 py-5 text-left last:border-0"><span className="text-[9px] text-black/35">{item.number}</span><span className={`font-serif text-2xl ${room===i?"text-[#18362d]":"text-black/55"}`}>{item.name}</span><ArrowUpRight size={16} className="ml-auto"/></button>)}</div><div className="mt-auto border-b border-black/10 py-7"><div className="grid grid-cols-3 gap-3 text-[8px] uppercase tracking-[.12em] text-black/40"><span>{rooms[room].guests}</span><span>{rooms[room].size}</span><span>{rooms[room].bed}</span></div><div className="mt-6 flex flex-wrap gap-2">{rooms[room].features.map(x=><span key={x} className="border border-black/10 px-3 py-2 text-[8px] uppercase tracking-[.12em] text-black/50">{x}</span>)}</div></div></div>
          </div>
        </div>
      </section>

      <div className="overflow-hidden border-y border-white/10 bg-[#18362d] py-4 text-[#e8ddca]"><div className="flex min-w-max gap-8 px-5 text-[9px] font-semibold uppercase tracking-[.2em]">{["Mountain views","Breakfast included","Private dining","Bonfire evenings","Forest walks","Mountain views","Breakfast included","Private dining"].map((x,i)=><span key={i} className="flex items-center gap-8">{x}<b className="text-[#c8aa7c]">✦</b></span>)}</div></div>

      <section id="experiences" className="bg-[#18362d] px-5 py-20 text-[#f3efe6] sm:px-8 md:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1560px]"><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#d7c19c]"><span className="h-px w-7 bg-[#c8aa7c]"/>Experiences / 03</div><div className="mt-7 grid gap-8 lg:grid-cols-[.65fr_.35fr]"><h2 className="font-serif text-[clamp(3.4rem,7vw,7rem)] leading-[.83] tracking-[-.055em]">The hills are<br/><em className="font-normal text-[#d7c19c]">part of the stay.</em></h2><p className="max-w-sm text-[13px] leading-6 text-white/45 lg:justify-self-end">Go outside. Walk slowly. Let the landscape decide the pace. Every experience begins close to the property.</p></div><div className="mt-12 grid gap-px bg-white/10 md:grid-cols-3">{experiences.map((item)=><article key={item.title} className="bg-[#18362d]"><div className="aspect-[4/5] overflow-hidden"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition-transform duration-700 hover:scale-105"/></div><div className="border-b border-white/10 p-5 sm:p-6"><div className="text-[8px] uppercase tracking-[.18em] text-[#c8aa7c]">{item.number} / {item.duration}</div><h3 className="mt-5 font-serif text-3xl">{item.title}</h3><p className="mt-3 text-[12px] leading-5 text-white/45">{item.description}</p><div className="mt-6 border-t border-white/10 pt-4 text-[8px] uppercase tracking-[.14em] text-white/30">{item.location} · {item.availability}</div></div></article>)}</div></div></section>

      <section id="dining" className="bg-[#f3efe6] px-5 py-20 sm:px-8 md:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1560px]"><div className="grid gap-12 lg:grid-cols-[.42fr_.58fr] lg:items-start"><div><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#536c5d]"><span className="h-px w-7 bg-[#536c5d]"/>Dining / 04</div><h2 className="mt-7 font-serif text-[clamp(3.4rem,7vw,7rem)] leading-[.84] tracking-[-.06em]">{dining.title}<br/><em className="font-normal text-[#536c5d]">{dining.titleAccent}</em></h2><p className="mt-7 max-w-md text-[14px] leading-7 text-black/55">{dining.description}</p></div><div className="relative"><div className="aspect-[4/5] overflow-hidden sm:aspect-[4/3]"><img src={dining.image} alt="Dining at The Hillview" className="h-full w-full object-cover"/></div><div className="absolute -bottom-6 right-3 w-48 bg-[#e6d8bf] p-4 sm:right-6"><div className="text-[8px] uppercase tracking-[.18em] text-black/40">Today at the table</div><div className="mt-3 font-serif text-xl">Slow food. Long evenings.</div><div className="mt-4 text-[8px] uppercase tracking-[.12em] text-black/45">Dinner / 19:00 — 22:00</div></div></div></div></div></section>

      <section id="gallery" className="bg-[#d8d0c1] px-5 py-20 sm:px-8 md:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1560px]"><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#536c5d]"><span className="h-px w-7 bg-[#536c5d]"/>Gallery / 05</div><h2 className="mt-7 font-serif text-[clamp(3.4rem,7vw,7rem)] leading-[.82] tracking-[-.06em]">A few views<br/><em className="font-normal text-[#536c5d]">worth keeping.</em></h2><div className="mt-12 columns-1 gap-4 sm:columns-2 lg:columns-3">{galleryImages.slice(0,6).map((item,i)=><figure key={i} className="mb-4 break-inside-avoid overflow-hidden bg-black"><img src={item.src} alt={item.alt} className={`w-full object-cover ${i%3===0?"aspect-[4/5]":"aspect-[4/3]"}`}/><figcaption className="flex justify-between bg-[#0f1814] px-4 py-3 text-[8px] uppercase tracking-[.16em] text-white/55"><span>{item.category}</span><ArrowUpRight size={13}/></figcaption></figure>)}</div></div></section>

      <section id="location" className="bg-[#f3efe6] px-5 py-20 sm:px-8 md:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1560px]"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#536c5d]"><span className="h-px w-7 bg-[#536c5d]"/>Location / 06</div><h2 className="mt-7 font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.83] tracking-[-.06em]">Far enough<br/><em className="font-normal text-[#536c5d]">to feel away.</em></h2><p className="mt-7 max-w-md text-[14px] leading-7 text-black/55">{hillview.description} Set in the hills, The Hillview is a quieter base for forests, valleys, villages and long drives through Arunachal Pradesh.</p><div className="mt-8 border-t border-black/10 pt-5 text-[9px] uppercase tracking-[.16em] text-black/45">{hillview.address}</div></div><div className="aspect-[4/5] overflow-hidden sm:aspect-[4/3]"><img src={galleryImages[7].src} alt="Mountain landscape" className="h-full w-full object-cover"/></div></div></div></section>

      <section className="bg-[#14251e] px-5 py-20 text-[#f3efe6] sm:px-8 md:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1560px]"><div className="grid gap-12 lg:grid-cols-[.58fr_.42fr]"><div><div className="flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[.22em] text-[#d7c19c]"><span className="h-px w-7 bg-[#c8aa7c]"/>Reservations / 07</div><h2 className="mt-7 font-serif text-[clamp(3.7rem,7vw,7rem)] leading-[.82] tracking-[-.06em]">Come up<br/><em className="font-normal text-[#d7c19c]">for a while.</em></h2><p className="mt-7 max-w-lg text-[14px] leading-7 text-white/45">Tell us when you would like to arrive. This concept is ready to connect to a live hotel booking engine or PMS.</p></div><div className="border border-white/10 bg-white/[.025]"><div className="p-5"><label className="block text-[8px] uppercase tracking-[.2em] text-white/30">Room</label><select value={rooms[room].name} onChange={(e)=>setRoom(rooms.findIndex(x=>x.name===e.target.value))} className="mt-3 w-full bg-transparent text-sm text-white outline-none">{rooms.map(x=><option key={x.name} className="bg-[#14251e]">{x.name}</option>)}</select></div><div className="border-t border-white/10 p-5"><label className="block text-[8px] uppercase tracking-[.2em] text-white/30">Guests</label><select value={guests} onChange={(e)=>setGuests(e.target.value)} className="mt-3 w-full bg-transparent text-sm text-white outline-none">{bookingOptions.guestOptions.map(x=><option key={x} className="bg-[#14251e]">{x}</option>)}</select></div><div className="p-5"><button onClick={()=>setSubmitted(true)} className="flex w-full items-center justify-between bg-[#e6d8bf] px-5 py-5 text-left text-[#18221d] hover:bg-white"><span><span className="block text-[9px] font-semibold uppercase tracking-[.18em]">Request a stay</span><span className="mt-1 block text-[11px] text-black/45">{rooms[room].name} · {guests}</span></span><ArrowUpRight size={16}/></button>{submitted&&<div className="mt-4 border border-[#c8aa7c]/20 p-4 text-[10px] leading-5 text-white/45">Request received for this demo. A production implementation would submit this to the hotel reservation system.</div>}</div></div></div></div></section>

      <footer className="bg-[#0e1713] px-5 pb-8 pt-16 text-[#f3efe6] sm:px-8 lg:px-12"><div className="mx-auto max-w-[1560px]"><div className="grid gap-12 md:grid-cols-[1.4fr_.6fr_.6fr]"><div><div className="text-[10px] font-semibold uppercase tracking-[.22em]">The Hillview</div><div className="mt-5 font-serif text-5xl leading-[.85] sm:text-7xl">Stay above<br/><em className="font-normal text-[#c8aa7c]">the clouds.</em></div></div><div><div className="text-[8px] uppercase tracking-[.2em] text-white/25">Explore</div><div className="mt-5 space-y-3 text-[10px] uppercase tracking-[.12em] text-white/55"><a href="#rooms" className="block">Rooms</a><a href="#dining" className="block">Dining</a><a href="#experiences" className="block">Experiences</a><a href="#gallery" className="block">Gallery</a></div></div><div><div className="text-[8px] uppercase tracking-[.2em] text-white/25">Contact</div><div className="mt-5 text-[10px] leading-6 text-white/50">{hillview.address}<br/>{hillview.email}<br/>{hillview.phone}</div></div></div><div className="mt-16 border-t border-white/10 pt-5 text-[8px] uppercase tracking-[.16em] text-white/25">Concept website / Built by Ganlary Labs · 2026</div></div></footer>
    </main>
  );
}
