"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, Menu, Plus, X } from "lucide-react";

const services=[["01","Home maintenance","Small repairs, upkeep and the jobs that never make the list.","From ₹1,200"],["02","Deep clean","A considered reset for kitchens, bathrooms and living spaces.","From ₹2,800"],["03","Garden care","Seasonal pruning, planting, cleanup and regular visits.","From ₹1,600"],["04","Move-in refresh","A complete pre-move service for a clean, ready home.","From ₹5,500"]];

export default function LocalServiceDemo(){
 const [menu,setMenu]=useState(false); const [selected,setSelected]=useState("Home maintenance"); const [size,setSize]=useState("2BHK"); const [frequency,setFrequency]=useState("One time");
 const estimate=useMemo(()=>{const base=selected==="Deep clean"?2800:selected==="Garden care"?1600:selected==="Move-in refresh"?5500:1200; const mult=size==="3BHK"?1.35:size==="4BHK"?1.7:1; const freq=frequency==="Monthly"?0.85:frequency==="Quarterly"?0.92:1; return Math.round(base*mult*freq).toLocaleString("en-IN")},[selected,size,frequency]);
 return <main className="min-h-screen bg-[#e7e1d3] text-[#233127]">
  <header className="border-b border-[#233127]/10"><div className="mx-auto flex h-[74px] max-w-[1460px] items-center justify-between px-5 sm:px-8 lg:px-12"><Link href="/demos" className="text-[8px] uppercase tracking-[.2em] text-black/40">← Demos</Link><div className="absolute left-1/2 -translate-x-1/2 text-center"><div className="font-serif text-xl">Field & Form</div><div className="text-[7px] uppercase tracking-[.25em] text-black/40">Home care · Guwahati</div></div><button onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="absolute right-4 top-[68px] z-30 w-64 border border-black/10 bg-[#e7e1d3] p-5 shadow-xl">{["Services","How it works","Service areas","Estimate","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase().replaceAll(" ","-")} className="block border-b border-black/10 py-4 text-[9px] uppercase tracking-[.18em]">{x}</a>)}</nav>}</header>

  <section className="mx-auto grid max-w-[1460px] gap-3 px-3 py-3 sm:px-5 lg:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[700px] overflow-hidden bg-[#2b3b30] sm:min-h-[800px]"><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1700&q=90" className="absolute inset-0 h-full w-full object-cover" alt="Beautiful home interior"/><div className="absolute inset-0 bg-gradient-to-t from-[#1e2a22]/75 via-transparent to-black/10"/><div className="absolute left-5 top-5 text-[8px] uppercase tracking-[.2em] text-white/55">01 / Field & Form</div><div className="absolute inset-x-5 bottom-7 sm:left-8"><h1 className="max-w-4xl font-serif text-[clamp(4.2rem,10vw,9rem)] leading-[.77] tracking-[-.07em] text-white">Your home,<br/><i className="text-[#c7a66a]">well kept.</i></h1><p className="mt-8 max-w-lg text-sm leading-7 text-white/55">Reliable people for the jobs that keep a home feeling good — from the small fixes to the seasonal reset.</p></div></div><div className="flex min-h-[700px] flex-col justify-between bg-[#d5ccb9] p-6 sm:p-10 lg:p-12"><div><span className="text-[8px] uppercase tracking-[.22em] text-black/40">A better local service</span><p className="mt-20 max-w-md font-serif text-[clamp(2rem,4vw,3.8rem)] leading-[.94] tracking-[-.04em]">Tell us the job. We&apos;ll take care of the <i>rest.</i></p></div><div className="border-t border-black/15 pt-5"><div className="grid grid-cols-3 gap-3 text-center text-[8px] uppercase tracking-[.13em]"><div><span className="block font-serif text-3xl">24h</span>reply time</div><div><span className="block font-serif text-3xl">4.9</span>rating</div><div><span className="block font-serif text-3xl">7d</span>available</div></div><a href="#estimate" className="mt-7 flex items-center justify-between bg-[#233127] px-5 py-4 text-[9px] font-semibold uppercase tracking-[.18em] text-white">Get an estimate <ArrowRight size={15}/></a></div></div></section>

  <div className="border-y border-[#233127]/10 bg-[#c7a66a] py-3"><div className="flex min-w-max gap-12 px-5 text-[8px] font-semibold uppercase tracking-[.26em]"><span>Trusted local team</span><span>Clear pricing</span><span>Background-checked pros</span><span>Easy scheduling</span><span>Trusted local team</span></div></div>

  <section id="services" className="mx-auto max-w-[1460px] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">02 / Services</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Good homes<br/><i>need care.</i></h2></div><div className="border-t border-black/15">{services.map(([n,name,desc,price])=><button key={name} onClick={()=>setSelected(name)} className={"grid w-full gap-4 border-b border-black/15 py-7 text-left sm:grid-cols-[60px_1fr_auto] "+(selected===name?"bg-[#ddd3c1]":"")}><span className="text-[8px] tracking-[.18em] text-black/35">{n}</span><span><strong className="font-serif text-2xl font-normal sm:text-3xl">{name}</strong><span className="mt-2 block max-w-md text-xs leading-6 text-black/45">{desc}</span></span><span className="text-sm">{price}</span></button>)}</div></div></section>

  <section id="estimate" className="bg-[#233127] px-5 py-24 text-[#e7e1d3] sm:px-8 md:py-32 lg:px-12"><div className="mx-auto max-w-[1460px]"><div className="grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-start"><div><span className="text-[8px] uppercase tracking-[.24em] text-[#c7a66a]">03 / Quick estimate</span><h2 className="mt-5 max-w-3xl font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Know the number<br/><i>before we visit.</i></h2><p className="mt-8 max-w-md text-sm leading-7 text-white/45">Choose a service and a few basics. This is an indicative estimate; we confirm the final scope before any work begins.</p></div><div className="bg-[#e7e1d3] p-6 text-[#233127] sm:p-8"><div className="text-[8px] uppercase tracking-[.18em] text-black/40">Service</div><select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-3 w-full border-b border-black/15 bg-transparent py-3 text-sm outline-none">{services.map(s=><option key={s[1]}>{s[1]}</option>)}</select><div className="mt-7 text-[8px] uppercase tracking-[.18em] text-black/40">Home size</div><div className="mt-3 grid grid-cols-3 gap-2">{["2BHK","3BHK","4BHK"].map(x=><button key={x} onClick={()=>setSize(x)} className={"border px-3 py-3 text-[9px] uppercase tracking-[.12em] "+(size===x?"border-[#233127] bg-[#233127] text-white":"border-black/15")}>{x}</button>)}</div><div className="mt-7 text-[8px] uppercase tracking-[.18em] text-black/40">Frequency</div><div className="mt-3 grid grid-cols-3 gap-2">{["One time","Monthly","Quarterly"].map(x=><button key={x} onClick={()=>setFrequency(x)} className={"border px-2 py-3 text-[9px] uppercase tracking-[.08em] "+(frequency===x?"border-[#233127] bg-[#233127] text-white":"border-black/15")}>{x}</button>)}</div><div className="mt-8 flex items-end justify-between border-t border-black/15 pt-6"><div><span className="block text-[8px] uppercase tracking-[.16em] text-black/40">Indicative from</span><span className="font-serif text-4xl">₹{estimate}</span></div><button className="bg-[#c7a66a] px-5 py-4 text-[9px] font-semibold uppercase tracking-[.16em]">Request visit</button></div></div></div></div></section>

  <section id="how-it-works" className="mx-auto max-w-[1460px] px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><span className="text-[8px] uppercase tracking-[.24em] text-black/40">04 / How it works</span><h2 className="mt-5 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Simple from<br/><i>start to done.</i></h2></div><p className="max-w-sm text-sm leading-7 text-black/50">No chasing. No mystery quotes. No wondering who is turning up at your door.</p></div><div className="mt-16 grid gap-3 md:grid-cols-3">{["Tell us what you need","We confirm the scope","We arrive & get it done"].map((x,i)=><div key={x} className="border border-black/10 p-6 sm:p-8"><span className="text-[8px] text-black/35">0{i+1}</span><h3 className="mt-16 font-serif text-3xl">{x}</h3><p className="mt-4 text-xs leading-6 text-black/45">{["Send a quick request with photos if useful. We reply with next steps.","You get a clear price, time window and the person handling the job.","Your home gets the attention it needs. We check the work before we leave."][i]}</p><div className="mt-8 flex items-center gap-2 text-[8px] uppercase tracking-[.16em] text-black/35"><Check size={12}/> No surprise charges</div></div>)}</div></section>

  <section className="grid lg:grid-cols-2"><div className="min-h-[560px] bg-cover bg-center" style={{backgroundImage:"url(https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1500&q=88)"}}/><div id="service-areas" className="bg-[#d5ccb9] p-8 sm:p-12 lg:p-20"><span className="text-[8px] uppercase tracking-[.24em] text-black/40">05 / Service areas</span><h2 className="mt-10 font-serif text-6xl leading-[.82] tracking-[-.06em] sm:text-8xl">Close to<br/><i>home.</i></h2><div className="mt-10 grid grid-cols-2 gap-y-5 border-t border-black/15 pt-6 text-[9px] uppercase tracking-[.15em] text-black/55"><span>Dispur</span><span>Beltola</span><span>Khanapara</span><span>Six Mile</span><span>Zoo Road</span><span>G.S. Road</span></div><p className="mt-8 text-xs leading-6 text-black/45">Not seeing your area? Send us your location and we&apos;ll confirm availability.</p></div></section>

  <footer className="bg-[#233127] px-5 py-10 text-[#e7e1d3] sm:px-8 lg:px-12"><div className="mx-auto max-w-[1460px]"><div className="flex flex-col justify-between gap-8 border-b border-white/10 pb-8 md:flex-row"><div><div className="font-serif text-3xl">Field & Form</div><div className="mt-1 text-[7px] uppercase tracking-[.24em] text-white/30">Home care · Guwahati</div></div><div className="flex flex-wrap gap-5 text-[8px] uppercase tracking-[.17em] text-white/40"><a href="#services">Services</a><a href="#estimate">Estimate</a><a href="#how-it-works">Process</a><Link href="/demos">All demos</Link></div></div><div className="pt-5 text-[8px] uppercase tracking-[.17em] text-white/20">Fictional local service concept · Ganlary Labs</div></div></footer>
 </main>
}
